### ISSUE TITLE
Bug in documentation about Template#binding

### ISSUE THREAD

**Issue by nickel** [tapquo/Lungo.js#1]
Hi!

First at all, nice work! I'm really enjoying to play with your framework.

I was trying to bind a template to a div but, as I see in the documentation, I should try with:

``` javascript
  lng.View.Template.binding('main', 'pending-tmp', data);
```

But I only got errors. Looking in the source code, I saw that the way is:

``` javascript
  lng.View.Template.Binding.create('main', 'pending-tmp', data);
```

Am I right?

Thank you again!

**Comment by soyjavi** [comment]
Hi!

Well, to create a template you must <code>:

```
lng.View.Template.create( id_of_template, markup_of_template);
```

For example:

```
lng.View.Template.create('pendint-tmp', '<li id={{id}}>{{name}}</li>');
```

I hope I've helped you :)

**Comment by nickel** [comment]
I did that in the view.js file but if I want to bind this template to a container... what's the best way?

**Comment by soyjavi** [comment]
I hope this will serve:

```
lng.View.Template.Binding.create({ container_id: 'main', template_id: 'list-tmp', data:{}or[] });
```

**Comment by nickel** [comment]
Great. As as wrote in the opening comment, so there is a little mistake in the doc.
