### ISSUE TITLE
Data-icon on Android Browser

### ISSUE THREAD

**Issue by Jumiluz** [tapquo/Lungo.js#10]
While testing your framework under my android tablet I stumbled across a rather odd behaviour:
all elements with a declared data-icon got and alphanumeric equivalent instead of the awaited icon.
For example: Home became the letter ''H', user 'U', refresh '0', storm 'e', trash '#'... etc.
Well, actually, any element with a class 'button', got its letter/character equivalent.

Of course, I also tested it with Firefox and Dolphin with the same results.

Thanks and keep up the good work!

Jumi

**Comment by soyjavi** [comment]
Yap... this is because your browser doesn't support font-face (CSS3 Feature). I'm sorry but data-icon requires this feature.

What version do you use?

Thanks

**Comment by Jumiluz** [comment]
I'm working with an Acer Iconia A500 with Honeycomb 3.2 using its default browser, as well as Mozilla Firefox and Dolphin Browser; all with the same behaviour. I'll get to you once I test it in Opera Mini web browser.

Thanks

**Comment by soyjavi** [comment]
Uhmm.. rare... We've Motorola Xoom, Asus Transformer and Samsung Tab... and works fine.

I'll test better.

Thanks for the info.

**Comment by Jumiluz** [comment]
Well, as expected, I also got problems with Opera Mini for android.
And, as already stated in another issue, coming back from landscape to portrait view or viceversa, ends up with a wrong footer toolbar layout.
Are indeed all these browsers CSS3 compliant, aren't them?

Thanks for your efforts.
