### ISSUE TITLE
Stats should be made optional and off by default

### ISSUE THREAD

**Issue by zrod** [tapquo/Lungo.js#100]
https://github.com/TapQuo/Lungo.js/blob/master/src/boot/Lungo.Boot.Stats.js

Really?

That should be optional, also it should be stated somewhere in the website.

I hate the fact that my users will have an additional useless "stalker" network request.

**Comment by jcuervo** [comment]
All you need to do is comment out line 20.

**Comment by vkarampinis** [comment]
Aggree with zrod.
That should be optional. Dont destroy this beatiful project with hidden http requests without developer know about that.

Think that many developers use the framework for private projects or even in offline mode.

Think again.
