### ISSUE TITLE
Range sliders freeze if not visible on iOS

### ISSUE THREAD

**Issue by jellea** [tapquo/Lungo.js#101]
In the app I'm building I'm using alot of range input fields. Some of the are not visible at first hand, they are below the scroll fold. After scrolling and showing them I'm not able to move them. It works perfectly at the desktop but I'm experiencing problems on iOS (device and simulator)

**Comment by soyjavi** [comment]
with lungo 2.0?

**Comment by jellea** [comment]
No, with version 1.0. Gladly 2.0 fixed it! Thanks!
