### ISSUE TITLE
Problems on Android 4.X navigation render

### ISSUE THREAD

**Issue by marcelaraujo** [tapquo/Lungo.js#102]
When I navigate thought pages, occurs an issue that breaks the layout and make it to slide up. This only occurs on this Android version and I can be able move all page like a photograph.

Screenshot below!
http://tinypic.com/view.php?pic=214plxd&s=6

**Comment by soyjavi** [comment]
Please update your proyecto to Lungo 2.0 :)

http://lungo.tapquo.com
