### ISSUE TITLE
lng.Data.Sql.insert ERROR

### ISSUE THREAD

**Issue by Jacen** [tapquo/Lungo.js#103]
Hay un error A la hora de ejecutar la insert.
values += (isNaN(value)) ? '"' + value + '"' : value;
Solo compruebas que sea o no un número, el fallo esta cuando el dato es una cadena vacia, que interpreta que es un numero, creando cadenas de sql que dan error, la solucion pasa por sustituirlo por esta cadena
values += (isNaN(value) || value=='') ? '"' + value + '"' : value;

**Comment by soyjavi** [comment]
Pull.Request?

**Comment by Jacen** [comment]
Espero haberlo  hecho bien.
