### ISSUE TITLE
Swipe events doesn't work on dynamic list elements 

### ISSUE THREAD

**Issue by ssdehero** [tapquo/Lungo.js#104]
I added a swipe event for a dynamically generated list item.Eg. Task item in your Demo 'ToDo.js'.
<code>
lng.dom('#done li, #pending li').swipeRight(function(event) {
        var todo_id = lng.dom(this).attr('id');
        App.View.todo(todo_id)
    });
</code>

But its not working.  but tap event for the same code is working...

Anyway I want to add a swipeRight to a dynamically generated list Item as the requirment. Reason or any suggestion..??

**Comment by soyjavi** [comment]
swipe event is equal to tap event (in gestures manager) ... I think the problem is other, could you paste your code here?

**Comment by soyjavi** [comment]
With the new version of QuoJS :)
