### ISSUE TITLE
Lungo 2.0 beta KitchenSink issues on iOS 6 devices

### ISSUE THREAD

**Issue by jsmanrique** [tapquo/Lungo.js#106]
I've been testing the 2.0-beta kitchensink demo (http://lungo.tapquo.com/test/index.html) on:
- iPod Touch 4th gen
- iPad 2

Both devices with iOS 6, and I have been having some issues:
- on iPod, the page kills the browser while loading, after showing I am using iOS 6 alert
- on iPad, I can load the page and even add it to my home screen, but scrolls don't work. It seems it tries to scroll the whole section

**Comment by christianmagill** [comment]
I have issues with checkmarks in kitchen sink for 2.0 and demo on website as well. The switch does not respond to swiping or tapping. Using iPhone 5 iOS 6

**Comment by FdezRomero** [comment]
Same situation with iPhone 4S and iOS 5.1.1: the switch checkboxes won't slide, just change their color and no icons are shown. Thanks.

**Comment by LucaBozzetto** [comment]
ipad 1 ios 5.1.1 and safari gets killed!

**Comment by jcuervo** [comment]
@FdezRomero - I changed the _changeCheckboxValue function from the Lungo.Boot.Events.js
<code>
    var _changeCheckboxValue = function(event)  {
        // event.preventDefault();
        var el = lng.dom(this);
        var new_value = el.val() > 0 ? 0 : 1;
        el.val(new_value);
        el.toggleClass("active");
    };
</code>

This worked on 5.0 and 5.1 but could not get the check and cross marks to display.
Touch responded as expected.

In my opinion, there should be a fallback when new input types like "range" is not fully supported on previous browsers.

**Comment by soyjavi** [comment]
Fixed in 2.1
