### ISSUE TITLE
<footer class="toolbar"> back from landscape mode

### ISSUE THREAD

**Issue by zot24** [tapquo/Lungo.js#11]
Al probar desde mi Android 2.3.5 (LG 2X)  (CM7) al entrar en modo "landscape" cargando el "footer" como "toolbar" y volver al modo vertical, los iconos del ejemplo del primer video tutorial que tenéis en Vimeo mantienen la disposición de cuando se encuentran en "landscape" por lo que solo se ve el primer icono y la mitad del segundo.

Un saludo.

Excelente trabajo ;)

**Comment by soyjavi** [comment]
[SPANISH]

No entiendo muy bien tu problema.. podrias subir el código a Github (nuestro amado github) y ver exactamente cual es el problema. Desde el equipo de @tapquo utilizamos tanto iOS (a partir de 4.0) como Android (2.2) y Android HoneyComb (3.1) y no hemos tenido ese tipo de problema.

Gracias por tu aporte.

**Comment by zot24** [comment]
[SPANISH]

Te comento y lo ilustro con unas capturas de pantalla, así como con el código que estoy ejecutando:

El siguiente enlace es el código que estoy ejecutando, lo obtuve siguiendo los pasos del vídeo tutorial: 

http://pastebin.com/ZuVME6NB

A continuación las capturas de pantallas donde podrás ver como se comporta el "footer" al pasar de una vista a otra (horizontal, vertical):

Captura de pantalla 1: (todo correcto, en vertical) http://dl.dropbox.com/u/198300/screenshot-1320768049356.png
Captura de pantalla 2: (toco correcto en horizontal) http://dl.dropbox.com/u/198300/screenshot-1320768059568.png
Captura de pantalla 3: (fallo al volver a la vista vertical) http://dl.dropbox.com/u/198300/screenshot-1320768065364.png

Se puede apreciar como al principio tenemos los 3 iconos debajo y después solo vemos 1 y parte del otro, es como si no se recuperase de su estado anterior (horizontal).

Espero haber aclarado el problema.

Muchas gracias, un saludo.

**Comment by soyjavi** [comment]
There is a new listener to capture when you rotate the device. (Release 1.0.1)

**Comment by zot24** [comment]
Thanks i'll try it!
