### ISSUE TITLE
Setting active state in aside navigation

### ISSUE THREAD

**Issue by alexcroox** [tapquo/Lungo.js#112]
If I'm using aside for a navigation menu, I can't find any documentation on switching the active state in a list to show which section the user is on:

```
<aside id="menu">
        <header data-title="Progress"></header>
        <article class="list">
            <ul>
                <li class="current">
                    <a href="#your-car" data-router="section">
                        <strong>Your car</strong>
                    </a>
                </li>
```

At the moment I'm guessing I have to listen to a tap event and do it myself?

```
lng.dom('#menu li a').tap(function(event) {
    $('#menu li.current').removeClass('current');
    add class current to parent li
});
```

Maybe there is an easier way I'm missing?

**Comment by alexcroox** [comment]
Actually I'm getting the impression it's not supposed to be used in this way. If I have 2 sections and link to them using a list in the aside as above, going back to the first section after being in the second section loads a black, blank screen.

I'm guessing this framework is built with new "pages" being almost windows over the main section, rather than actually switching to a new section and treating it as a page rather than a "popup". I can't find any examples in your kitchen sinks that utilise the functionality I am looking to achieve.

You can see this issue in my example here:

http://alexcrooks.me/others/lungo
1. Open menu and touch "about you"
2. Open menu and touch "your car"

Loads blank, black screen

**Comment by alexcroox** [comment]
OK this was actually a fundamental misunderstanding on my part. I should have been using articles not sections. Once I switched to using that it worked as intended. Awesome!

**Comment by soyjavi** [comment]
It is as you say, the correct navigation in this case is via article :)
