### ISSUE TITLE
Wobbly aside transitions when using form elements

### ISSUE THREAD

**Issue by alexcroox** [tapquo/Lungo.js#113]
The transitions of opening and closing the aside when the article has form elements on it is very wobbly.

You can see this here in the iOS simulator, the effects are even greater on my actual iPhone 5 iOS6 device.

http://al3x.me/KNZ5

The code can be tested here:

http://alexcrooks.me/others/lungo/2_0

Use a real mobile device to see the effects magnified.

**Comment by alexcroox** [comment]
OK I've narrowed it down to 2 form elements causing issues. RANGE and CHECKBOX elements both cause the wobbling transitions. If you remove those 2 elements from the form there are no issues.

**Comment by soyjavi** [comment]
Please check with final release :)

https://github.com/downloads/TapQuo/Lungo.js/lungo.2.0.0.zip
