### ISSUE TITLE
iOS - Black screen on view change

### ISSUE THREAD

**Issue by jashsayani** [tapquo/Lungo.js#116]
It works perfectly on Desktop but shows black screen on iPhone.

<a href="#add" data-target="section" data-icon="plus" class="button onright"></a>

**Comment by soyjavi** [comment]
Show me your code :)

**Comment by jashsayani** [comment]
I was just using an "a" tag with href pointing to section. But I found a workaround, using "onclick" with LUNGO.router.section() and LUNGO.router.back() solves this issue. By the way, I tested this on the iPhone 5.

**Comment by soyjavi** [comment]
I don't understand your problem... "click"? this event doesn't exists in
MobileDevices :)

2012/11/14 Jash Sayani notifications@github.com
