### ISSUE TITLE
Android - The scroll is greater than the section

### ISSUE THREAD

**Issue by Ndpnt** [tapquo/Lungo.js#118]
Since I use Lungo 2.0 I have a problem on my application. Now on android browser (Android: 2.3.7), the scroll is greater than the section height and I can scroll below the footer…
I didn't have this problem with Lungo 1.2

I also test your demo app there is the same problem.

**Comment by serhiihordiichuk** [comment]
Also have this problem on Android 4.0.3 
On iOS work fine.

**Comment by manuelllop** [comment]
I have the same problem on android 4.0.3

**Comment by abrahammartin** [comment]
Same here (Google Chrome and Google Chrome Canary).

Seems that the css rule

footer ~ article{bottom:44px;}

is not applied.

**Comment by soyjavi** [comment]
Upgrade to Lungo 2.1

**Comment by mserranog** [comment]
I'm having the same issue in Android 4.0.3, in Android 2.2 works fine. Using browsers works fine in Firefox Mobile, not in Default Android Browser. I have Lungo 2.1. It is corrected?

**Comment by jeroenpeters1986** [comment]
I am also having this. It is with lungo 2.2, kitchen sink version: '2.1.0222',

My Android version is 4.0.4 btw
