### ISSUE TITLE
Blackberry icons problem

### ISSUE THREAD

**Issue by zot24** [tapquo/Lungo.js#12]
Al visualizar el primer ejemplo de los vídeos tutoriales de Vimeo desde una Blackberry 9300 (versión 6.0) no carga los iconos correctamente:
- data-icon="cloudup" 
- data-icon="user"
- data-icon="config"

En vez de esos iconos muestras letras Y, C, L.

Un saludo.

**Comment by soyjavi** [comment]
[SPANISH]
UHmmm... Eso es porque tu navegador no soporta @font-face (una característica de CSS3), intenta actualizar el S.O. Ya que la idea de LungoJS es que sea utilizado en Móviles con verdadero soporta a estas nuevas tecnologías.

Gracias por su aporte.

**Comment by zot24** [comment]
[SPANISH]

Actualizo y te comento a ver si me funciona correctamente.

Entiendo que solo habéis hecho pruebas sobre los 3 dispositivos que me comentabas en la otra issue ¿?
"iOS (a partir de 4.0) como Android (2.2) y Android HoneyComb (3.1)"

Muchas gracias!

**Comment by magojhonblack** [comment]
Hola les cuento que tengo problemas con los iconos lo he probado en dispositivos iphone 4.0.1 y 4.,  blackberry 5, 6 y 7 y con ningún he tenido resultados positivos hay manera de utilizar iconos propios  como imágenes png para que se adapten a este framework.
