### ISSUE TITLE
Compatibility problems in Android 4.2

### ISSUE THREAD

**Issue by FdezRomero** [tapquo/Lungo.js#120]
Hi @soyjavi,

I just got my hands on a new Google Nexus 4 and one of the first things I did was launching the Lungo Demo in the default browser (Chrome). Here are some broken features I've seen so far:
- The side buttons in the nav bar are always blurry, both vector icons and text (back) as opposed to the crisp title header. I think it might be related to the CSS `-webkit-font-smoothing: antialiased` property.
- The range form element won't slide when swiping, it would only work by tapping at the desired position.
- The checkboxes work great by tapping but they break when swiping: the state of the checkbox (color, symbol and its position) is properly determined but the actual button doesn't slide. It won't fix after that, even by tapping on it.
- The `swipe`event (as well as `swipeLeft`, `swipeRight`, `swipeUp` and `swipeDown`) is not recognized, but the `swiping` event works ok.

Let me know if you need some screenshots (I'm not sure if I can attach images or links here).

Greetings!

**Comment by 0xc1c4da** [comment]
Has there been any progress on this? Android 4.7 under emulator doesn't work at all, 2.3.3 does, however.

**Comment by soyjavi** [comment]
Fixed in 2.2

**Comment by roymi** [comment]
There's no scrolling on the Nexus 4... At least the one I'm using. (Android version 4.2.2)
The scrolling on version 1.2 works great
also on version 2.1, but the 1.2 has a better performance (I think you used iScroll?, there's a new version 5)
iScroll works best for all devices I've been testing... if you could turn back to that solution

**Comment by ryaninmotion** [comment]
hi, i'm new to develop lungojs. Where is the stable version of android to running lungojs ?

Best Regards,

Ryan Martin Martono
