### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Mich93** [tapquo/Lungo.js#123]
If I add a footer to the example page and click button 1, then 2 and then again button 1 i get a black screen.

**Comment by yawnt** [comment]
+1

**Comment by grigorov** [comment]
Lungo 2.1?

**Comment by Mich93** [comment]
Yes...but I've already fixed it!
Anyway, thanks a lot!
Stefano

-----Original Message-----

**Comment by maxaud** [comment]
Mich93, for others who may have the same problem or if it's a problem with the files, please share your solution. Thank you.
