### ISSUE TITLE
The default browser in Android 4.2 version for sale in the Republic of Korea, scrolling does not work properly, swipe, rotate, pinch event does not work at all.

### ISSUE THREAD

**Issue by myso-kr** [tapquo/Lungo.js#124]
Lack of English proficiency, Please note that the problem through a translator.

The default browser in Android 4.2 version for sale in the Republic of Korea, scrolling does not work properly, swipe, rotate, pinch event does not work at all.

"event.preventDefault ()", "event.stopPropagation ()"
Seemed to be adequately addressed using the above two methods.

Rapid updates to satisfy many users and developers.

In addition,
JQuery Loader Plugin Lungo apply to "PhoneGap" I have produced.

Loader Example: http://www.myso.kr/work/jquery_lungo/

**Comment by soyjavi** [comment]
Please check new version 2.1 :)
