### ISSUE TITLE
switch buttons not working on some browsers

### ISSUE THREAD

**Issue by radare** [tapquo/Lungo.js#131]
there are some issues using switch elements on firefox and mobile safari, they are wrongly rendered or just respond incorrectly. on android and chrome seems to work fine.

**Comment by radare** [comment]
I have also tested lungo on firefoxOS and fails as expected too. you can see an screenshot here:

http://lolcathost.org/b/r2ffos.png

**Comment by soyjavi** [comment]
I'll improved it in Lungo 2.1 (January 2013).
