### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by rafaelmotta** [tapquo/Lungo.js#136]
Lungo is cool, but the documentation is quite weak. In my opinion, one of the most important things when choosing a framework is documentation.

It was very difficult for me to choose lungo instead of jQuery Mobile, since there is only a single page of documentation, that does not explain much. Almost everything I know about the Lungo is because the demo on the home page, and also for having inspected the source code on github.

How about we create a new documentation page, more complete, like Twitter Bootstrap / jQuery Mobile?

I would like to help, if you approve.

Lungo is a very interesting project, and I believe adequate documentation would give an interesting turn on this project.

**Comment by FdezRomero** [comment]
I agree with Rafael's suggestion: the current documentation doesn't cover
everything that you later see in the examples. An introduction to the
development strategies with Lungo and an overview of the structure would be
really appreciated by newbies.

**Comment by mattblac** [comment]
I definitely agree. I would love to see the documentation greatly expanded upon, and would also be willing to help in whatever way I can. I think in the development world, the more hand-holding, the better!

I've only been using lungo for a week or so now, and most of what I've learned thus far has come from a mix of what is available in the documentation, and then altering the source code of the demo to observe from cause and effect.

**Comment by terox** [comment]
I agree with rafaelmotta, FdezRomero and mattblac. Since Lungo 1.0 the documentation is very poor. jQuery Mobile and other similar frameworks have a lot of examples with different configurations. All class attributtes well-documented and many examples not only the basic implementation ;)

**Comment by grigorov** [comment]
I agree with terox,afaelmotta, FdezRomero and mattblac. Documentation very poor. QuoJS is not bad, monocle poor documentation. Can you prepare documentation, where LungoJS + Monocle + QuoJS in box, Templates in LungoJS based on Monocle, but how is work, i'm not understand. Can you prepare more complete documentation about LungoJS. Thanks for your work. If need help, to translate on Russian language, can help.

**Comment by cytec** [comment]
i totaly agree with that.

the documentation is verry basic atm, and if you like to use templates (like back in 1.2) you now have to use Monocle which is documented poorly and i was not able to find some examples for it. There is a video instruction which shows how to use it but its only available in spanish, so nothing i can work with :(

**Comment by grigorov** [comment]
cytec can you get url of spanish video, where show lungo 2.x and Monocle??? i can't find this video.

**Comment by koldomac** [comment]
It is here:
http://www.youtube.com/watch?v=gFATYusqPM0

**Comment by rodrigobarona** [comment]
Yes, I agree this more documentation. Is a very great project but we need some more help to improve it ;)

Thanks

**Comment by giorrrgio** [comment]
:+1:

**Comment by peregrinogris** [comment]
Honestly, lack of documentation is the reason I'm not starting with Lungo. It seems pretty nice as a library, but the available docs just scrap the surface of its capabilities.
Having to look into the source code to know how to use it in something a little more complex than a simple demo page is just too time consuming, considering Bootstrap's excellent docs for example.

**Comment by soyjavi** [comment]
We're working on it.

**Comment by soyjavi** [comment]
Launched! :)

https://groups.google.com/forum/#!topic/lungojs/EoZPslyE7fE
