### ISSUE TITLE
WebSQL is deprecated! :S

### ISSUE THREAD

**Issue by marcalj** [tapquo/Lungo.js#14]
https://groups.google.com/a/chromium.org/group/chromium-html5/browse_thread/thread/9e8e9262a973f36d/9ad2883f70fac682

Hi, I see that you use WebSQL, but this is a deprecated functionality in favor of IndexedDB.

https://groups.google.com/a/chromium.org/group/chromium-html5/browse_thread/thread/9e8e9262a973f36d/9ad2883f70fac682

It's a known problem?

**Comment by soyjavi** [comment]
I know, but IndexedDB is not supported in Mobile Device... and WebSQL does have support. Both Google and Apple have said that WebSQL continue in their browsers.

**Comment by marcalj** [comment]
Mmmm ok, but this implies that we need a way to manage db migrations. I think it's a huge problem in conjuction with a applicationCache...

Personally probably wouldn't use it but it never knows... Thanks!
