### ISSUE TITLE
Support for Windows Phone 8

### ISSUE THREAD

**Issue by kraftwer1** [tapquo/Lungo.js#142]
Right now, the provided example doesn't work on Windows Phone 8. Neither it does in Windows Phone 7, even though it claims to.

Any information about when it will be supported?

**Comment by FdezRomero** [comment]
The latest commit doesn't work on iOS or desktop Chrome either: I guess it's just in an unfinished state, so it may not be due to lack of support.

**Comment by kraftwer1** [comment]
Sorry, I meant the example provided on your website, not the one in the Master branch. (Is there any revision that is compatible with Windows Phone?)

**Comment by soyjavi** [comment]
No, not in plans.

**Comment by cpursley** [comment]
I recommend reconsidering Windows Phone 8 and Windows 8 (touch) support. Windows Phone 8 adoption has been pretty good and it looks like it will become the third most adopted mobile OS.

**Comment by soyjavi** [comment]
I disagree, Microsoft currently has a poor browser on Windows Phone. I'd rather bet on powerful browsers such as BlackBerry10 or FirefoxOS.

**Comment by endareceo** [comment]
I agree with cpursley, Windows Phone is not to be neglected if you want Lungo to compete with jQuery Mobile.

**Comment by soyjavi** [comment]
Sorry, but it is our decision, now we are focused on Webkit and Mozilla engines ... trying to create the best experience in mobile, tablet or TV devices.

**Comment by endareceo** [comment]
I respect the fact that it's your decision. However from a commercial point of view this is a bit of an issue preventing my company from using Lungo for HTML5 app projects. My clients don't care a single dime for Firefox or Firefox OS, but they have Windows 8 and Windows Phone devices.

Don't get me wrong: I am a major fan of your framework and I use it whenever I can in projects. In fact I want to use it in more projects, that's why I am asking/nagging.

**Comment by soyjavi** [comment]
The big problem that exists with Windows8 (mobile) its the poor browser :/

**Comment by endareceo** [comment]
What part of Lungo is causing the incompatibility with Windows Phone 8? I am willing to look into it.

**Comment by soyjavi** [comment]
The incompatibility it's the touch support in Windows Phone 7/8 Mobile … gesture events.

**Comment by cpursley** [comment]
Windows support is still a vital business requirement, unfortunately - especially tablet and desktop.

**Comment by ayzenquwe** [comment]
But there are several UI libs that work fine with Windows Phone 8 (I mean gestures). We are trying to make a decision whether to use your framework and the main "stopper" is no support for Windows Phone 8 in the near future.

**Comment by maxaud** [comment]
I too would love Windows Phone 8 Support, or at least partial support for UI elements.

**Comment by cpursley** [comment]
Maybe the solution is to fork the lungo project and use a separate touch library for IE? Detect if the device is IE and point at a separate set of css/javascript?

**Comment by soyjavi** [comment]
Noup, remember that QuoJS it's the CORE of LungoJS …

**Comment by webprofusion-chrisc** [comment]
Hi guys, I need IE support too, specifically to develop cross platform between mobiles and windows 8 desktop and windows phone 8. Here are some tips for IE touch handling: http://blogs.windows.com/windows_phone/b/wpdev/archive/2012/11/15/adapting-your-webkit-optimized-site-for-internet-explorer-10.aspx#step4 I'm guessing you primarily develop on a Mac and don't have access to the Windows Phone SDK (it has an emulator with touch events). So it sounds like quojs is the library which needs some work for IE?

**Comment by cpursley** [comment]
I suppose those of us familiar with IE touch library should fork the quojs project or lungo and utilize a different touch library. Just a cursory look at Google analytics show about 75% of my hits are IE users.

**Comment by muhlegg** [comment]
Windows 8 support is unfortunately a must have these days. Was really exited when I found this framework but now I won't be able to use it. I already started writing a mail to you regarding your commercial licensing but no need to even send it now. Hope to see you change your mind soon ;)

**Comment by soyjavi** [comment]
Not for now …. We feel Open Source as part of our lives, and Microsoft don't. So we love webkit, firefox because it's OpenSource...
-- 
Javi Jiménez Villar
Founder at @tapquo

On 26 de octubre de 2013 at 09:58:59, Filip Holmberg (notifications@github.com) wrote:

Windows 8 support is unfortunately a must have these days. Was really exited when I found this framework but now I won't be able to use it. I already started writing a mail to you regarding your commercial licensing but no need to even send it now. Hope to see you change your mind soon ;)

**Comment by muhlegg** [comment]
Understand your point. Just too bad, especially when you live up north where Windows phones(nokias) are really popular :/

**Comment by soyjavi** [comment]
I'm sorry but but Windows Phone aren't more popular than iOS and Android. Take a look to the use and consumption statistics to understand it.
-- 
Javi Jiménez Villar
Founder at @tapquo

On 26 de octubre de 2013 at 10:14:43, Filip Holmberg (notifications@github.com) wrote:

Understand your point. Just too bad, especially when you live up north where Windows phones(nokias) are really popular :/

**Comment by endareceo** [comment]
Then I guess you should stop supporting Firefox OS as well? I get your affection for open source, but we are running business and have to listen to clients. If a clients wants Windows Phone we make it happen. And in a way we are your clients so...

Anyway, I stopped using Lungo.js for a couple of reasons. This attitude has been one of them.

**Comment by soyjavi** [comment]
FirefoxOS is a good opportunity to purchase low-cost smartphones (especially in countries in process of improvement) and the most important is Open Source. At @tapquo also serve clients ... and we have no problems with them.

Anyway if you want to use Lungo in WIndows Phone is very simple, fork the project and start to make the port :)

regards,
-- 
Javi Jiménez Villar
Founder at @tapquo

On 26 de octubre de 2013 at 11:19:42, Bram Vandewalle (notifications@github.com) wrote:

Then I guess you should stop supporting Firefox OS as well? I get your affection for open source, but we are running business and have to listen to clients. If a clients wants Windows Phone we make it happen. And in a way we are your clients so...

Anyway, I stopped using Lungo.js for a couple of reasons. This attitude has been one of them.

**Comment by muhlegg** [comment]
Did not say Windows were more popular at any stage... just pointed out that if you have to make a app for "all" mobile users you can't ignore Windows. Especially here in Finland Windows Phones are really popular, of course due to the power of Nokia. I did see some roadmap somewhere where Windows was included but I guess that path has changed since then.
