### ISSUE TITLE
PinayPunto changes have broken Lungo

### ISSUE THREAD

**Issue by qmanning** [tapquo/Lungo.js#143]
The new "example" demo doesn't work at all - on phone or in browser. Please rectify or revert back to previous branch.

**Comment by haas85** [comment]
PinayPunto is a member of the taqpuo tapquo team. Lungo 2.1 is still in
development, so we are still doing modifications, so it's not a stable
release.

2013/1/24 qmanning notifications@github.com

**Comment by soyjavi** [comment]
PinaYPunto works at Tapquo, and we're working in branch... if you want a stable version download 2.0.
