### ISSUE TITLE
Icons are disappeared on BlackBerry playbook

### ISSUE THREAD

**Issue by alikrc** [tapquo/Lungo.js#145]
After installing the example app, no icons are displayed all over the app. I think its connected with base64 encoding. Can you provide some information to fix this?

**Comment by maxaud** [comment]
I got this because the filename for the icon css file has capital letters but they are referenced with lowercase (or vice-versa).

Try changing that and see if it works for you as it did me.

**Comment by alikrc** [comment]
Yes great, it's working.now, Thanx.

**Comment by maxaud** [comment]
Cool, glad I could help.
Forgot to make a separate issue for it here when I found the problem.

**Comment by alikrc** [comment]
@soyjavi you should fix the error on source code. path: "example / components / lungo / " please rename these files as:
 "Lungo.icon.brand.css"  ->  "lungo.icon.brand.css"
"Lungo.icon.css" --> "lungo.icon.css"

or problem will be unsolved.
