### ISSUE TITLE
Aside doesn't scroll

### ISSUE THREAD

**Issue by rkorobeynikov** [tapquo/Lungo.js#147]
I've tried your example at http://lungo.tapquo.com/example/ and aside doesn't scroll.
Safari ios 5.0, iphone.

**Comment by maxaud** [comment]
I have the same problem on iPad.

**Comment by soyjavi** [comment]
Tested in Safari ios 5+ and running :/.

More info please, we've tested on iPad/2/Mini, iPhone 4/4s/5, iPodTouch 3g

**Comment by rkorobeynikov** [comment]
Scrolling at aside leds to scrolling all page.
![image](https://f.cloud.github.com/assets/3233942/131479/0dc0e208-705c-11e2-9e41-a71e836b4189.jpeg)
iPhone 4, iOS 5.0.1
I tested also on iPhone 4s, iOS 6.1 and iPhone 4 iOS 6.0, both running fine.

**Comment by soyjavi** [comment]
I'll check

**Comment by ezekielchentnik** [comment]
im seeing this too.

**Comment by yaoquan** [comment]
I'm seeing this too. Any news on this?

**Comment by soyjavi** [comment]
I'm working on Lungo.Brownie (2.2) :)

**Comment by soyjavi** [comment]
Fixed in 2.2
