### ISSUE TITLE
Aside not reverting on demo

### ISSUE THREAD

**Issue by maxaud** [tapquo/Lungo.js#148]
When viewing the demo on the homepage and you go to the asides demo page and click on the normal aside example, upon returning to the app home screen, the original aside contents arent repopulated. 

On a side note, the aside content now seems to slide in after the aside.. This looks weird in my opinion. Is that the intended result?

Thanks!

**Comment by soyjavi** [comment]
Yes, it is the desired effect ... I'm testing new effects for aside :)
