### ISSUE TITLE
Browser "Back" buttons not working, hash changes not updating view.

### ISSUE THREAD

**Issue by dustmoo** [tapquo/Lungo.js#149]
In Safari, Mobile Safari and Chrome (Every browser I have tested) Lungo does not handle the "back" button of the browser properly.

The #hash in the location changes, but the view does not update to reflect the change.

The app I am developing will be appearing both in browser from a server and as stand alone apps, I don't want to make the assumption that the browser based users will always use my navigation buttons.

Can you help me get this resolved? :)

Thanks!

Dustin

**Comment by dustmoo** [comment]
Also, I have noticed that sometimes I need to click a control twice in order for the view to change in Mobile safari.

The first time will change the hash but not the view, second click works.

**Comment by icyflash** [comment]
It looks like Lungo didn't implement HTML5 History API.

**Comment by soyjavi** [comment]
You're right Lungo don't implemente History API, has own API called router.

**Comment by dustmoo** [comment]
Do I need to use Router manually to have the #hash history behavior work? Either way it is implemented is fine, I just can't figure out how to set it up yet.

**Comment by thertweck** [comment]
Are there any affords on this issue? It would come really handy together with Cordova on Android devices.

**Comment by i8ramin** [comment]
I am also interested in this. It is fine to say that we need to implement this ourselves and possibly point to some tutorial or something. Thanks!

**Comment by alejandro** [comment]
@soyjavi Why this is closed? I think it's a must in a framework like this. Or  Is there a workaround with the "Router API"?

BTW not only in browsers because I'm testing in mobile devices.

**Comment by TsubasaOzora** [comment]
get this problem too. :(

any solution ?
