### ISSUE TITLE
Considering a mix with Backbone.js

### ISSUE THREAD

**Issue by marcalj** [tapquo/Lungo.js#15]
Hi, I've recently met your project and I find it really awesome (thanks to the screencasts :P).

I'm considering jQuery mobile for my next projects, but with your project, I have doubts... :)

I'm worried about the template and server communication.

I'm using Backbone (http://documentcloud.github.com/backbone/) a lot with a couple of projects, and I think is a MUST for some functionalities.

I don't know if you plan to be templates and server-side data-retrieval agnostic or will implement it as the core system.

Backbone use underscore.js, that use a system for templates, but also there's a jQuery tmpl in the place....

What are your focus for this issues? (template system and REST services data retreival).

PD: Backbone has a View element that use a event system, router system and so on...
PD: Sorry if it's not the right place for this question.

Salut! des de Barcelona.

**Comment by soyjavi** [comment]
In future versions I will consider now I want to offer a valid experience in applications without a web-server.

**Comment by marcalj** [comment]
Ok cool, this night in bed I thought that will be awesome to create a independent plugin for LungoJS that has the same functionalities++ of Bachbone, so you can use it with LungoJS or not.

Backbone is great, but their development is really slow. If you create a independent plugin probably will catch the attention of all the backbone users, and your project will going mainstream quickly... just dreaming :P

**Comment by soyjavi** [comment]
Dreaming is the beauty of this life. :)
