### ISSUE TITLE
menu icon is wrong

### ISSUE THREAD

**Issue by stela5** [tapquo/Lungo.js#150]
Your use of the three vertical blocks icon for the menu is confusing.  The mobile standard is three horizontal lines (see http://mobile.smashingmagazine.com/2012/10/08/the-semantic-responsive-design-navicon/ and http://www.insidefacebook.com/wp-content/uploads/2011/09/Bookmarks-Menu.png).  The three vertical blocks are an Android pattern for overflow navigation.  Your use of a common icon for a different design pattern is confusing to our Android users.

**Comment by maxaud** [comment]
I like the 3 blocks...

**Comment by FdezRomero** [comment]
I agree with @stela5. By using this icon, Android users are expecting a vertical drop-down menu and not a lateral opening aside. This also affects BB10 users as indicated in their UI Guidelines: https://developer.blackberry.com/design/bb10/screen_structure.html

**Comment by soyjavi** [comment]
Sorry but there is no pattern that forces use your icon that has been designed for aside reference (because really its elements are arranged vertically).

In case you want another icon, can create their own font-face :)

**Comment by stela5** [comment]
I guess the beauty of open source is the ability to modify the UI to whatever suits our needs best.

For anyone taking soyjavi's advice and designing your own font-face, here are popular design patterns that may clash with Lungo's "aside" icon and therefore should be avoided when choosing your own menu icon:

iOS -- three horizontal dots refer to a "More view controller":
http://developer.apple.com/library/ios/#documentation/WindowsViews/Conceptual/ViewControllerCatalog/Chapters/TabBarControllers.html
see also Table 7-4: http://developer.apple.com/library/ios/#documentation/userexperience/conceptual/mobilehig/UIElementGuidelines/UIElementGuidelines.html

Android -- three vertical blocks refer to an "action overflow":
http://developer.android.com/design/patterns/actionbar.html

BlackBerry -- three vertical dots refer to an "action overflow":
https://developer.blackberry.com/design/bb10/screen_structure.html
http://btsc.webapps.blackberry.com/btsc/viewdocument.do?externalId=KB00510

Microsoft -- four squares (grid) refer to the main menu:
http://keynotopia.com/keynotopia-3-2-update-windows-8-templates-for-keynote-and-powerpoint/

P.S. As soyjavi correctly pointed out, there is no requirement to use the three bar icon for menus or asides, but this link summarizes a number of references that strongly support a growing consensus: http://css-tricks.com/three-line-menu-navicon/
