### ISSUE TITLE
PHP file loads on desktop computer but not mobile devices

### ISSUE THREAD

**Issue by jamesdowen** [tapquo/Lungo.js#151]
I'm attempting to load in a .php file with this new Lungo framework which I've took a great fancy to. I'm using a link as follows:

! attached
![serdyit](https://f.cloud.github.com/assets/3462628/121751/2b1e368a-6def-11e2-9bd0-1dac6685ce50.PNG)
!

But it's only working on desktop, not iOS or Android. I still get the loader pop up, but then it disappears and nothing has happened.

**Comment by soyjavi** [comment]
Cross-Domain???
