### ISSUE TITLE
not working on phonegap android 4.1.x

### ISSUE THREAD

**Issue by chekun** [tapquo/Lungo.js#152]
Have you guys test on android 4.1.x with phonegap?
i have tested, failed.
first icons have no apperance , due to css file name case senstive problem
then i click sidebar icon on the nav section, failed
logcat shows page reloaded and not run as expeced.
here are some screenshots.
can you guys help me solve this?
![QQ 20130205095953](https://f.cloud.github.com/assets/1967804/126105/c65411f8-6f37-11e2-8e0b-a6fcde5bdecc.png)
![QQ 20130205100154](https://f.cloud.github.com/assets/1967804/126109/0cdf1442-6f38-11e2-99f1-d8ac7659c2c7.png)

**Comment by soyjavi** [comment]
Yes we've tested on Android 4\* :) and running perfectly (issues in some device with scrolls). I don't know what's your problem, but I think it's in your phonegap configuration.

**Comment by chekun** [comment]
yes, my bad, turns out to be my android emulator issue, tested on my phone , works just fine.

**Comment by soyjavi** [comment]
:)

**Comment by 0xc1c4da** [comment]
We've tried Sony Xperia tipo (4.0.4) and Samsung Galaxy Tab 2 7.0 (4.0.3) - didn't work on both

**Comment by mserranog** [comment]
I have an issue when scrolling in my Nexus S (Android 4) in an installed apk and using web browser too. In Android emulator works fine. For example, when I scroll down in a list and I clicked an item it redirects to another item. Using Lungo 2.1

Edit: In Firefox Mobile working fine

**Comment by soyjavi** [comment]
Show me your code and I'll help you :)

**Comment by mserranog** [comment]
Web application here: http://bartrebolf7.x10.mx/AppBarTrebolF7 (For example: click on "Noticias" or in "El Equipo" -> Jugadores). When there is a list with scroll, if you scroll until the last element, the scroll continues and if you tap on the last element it is like you are clicking the element supposed to be in that position if there isn't more scroll. It happens in my device with Android 4.0.3 using default browser or in the generated .apk. Not having these problems using laptop, with Firefox Mobile or Android 2.2. Thanks!

Edit: the same with Kitchensink in the main screen.
