### ISSUE TITLE
icons disappear when switching back to a section via data-async

### ISSUE THREAD

**Issue by stela5** [tapquo/Lungo.js#153]
1. Create three pages: index.html, page1.html, page2.html
2. On page1.html and page2.html in the section create a nav footer:

```
    <footer><nav>
    <a href="#page1" data-icon="home"  data-router="section" data-async="page1.html" class="active"></a>
    <a href="#page2" data-icon="share" data-router="section" data-async="page2.html"></a>
    </nav></footer>
```
1. index.html loads page1.html:
   Lungo.init({name: 'example',resources: ['page1.html']});
2. App loads page1.html as expected
3. After clicking on second footer icon, page2.html loads as expected
4. After clicking on the first footer icon (home), the page1.html section loads but all the icons are missing.  Clicking on second footer box loads page2.html but again without any icons.

**Comment by soyjavi** [comment]
Please check v2.2
