### ISSUE TITLE
icons don't render on Android (in the example app)

### ISSUE THREAD

**Issue by ghost** [tapquo/Lungo.js#154]
There are two CSS files which are named Lungo.icon.css and Lungo.icon.brand.css, the L should not be capitalized otherwise they don't work locally from Android since its file names are case sensitive. It works from a web server though.

**Comment by maxaud** [comment]
This has been brought up here as well and not addressed:
https://github.com/TapQuo/Lungo.js/issues/145

**Comment by soyjavi** [comment]
case sensitive, in 2.2 it's fixed by default :)
