### ISSUE TITLE
Pull and refresh not scrolling on Android 2.3.5

### ISSUE THREAD

**Issue by mezinitia** [tapquo/Lungo.js#156]
Hi, I'm evaluating using Lungo.js - currently looking for a replacement for jQuery mobile. Unfortunately Lungo has some issues on Android 2.3, of which there are still a very large number of users.

Testing on Android 2.3.5 Galaxy SII

In the kitchen sink app the following Pull and Refresh demo does not work properly

Scroll down for pull and refresh bit works, but if you try and scroll the page up to view more content it scrolls up but the bottom content is masked by black.

**Comment by mezinitia** [comment]
There is an Android build of this here that you you can try if you have an old Android handset or emulator
 https://dl.dropbox.com/u/579708/android/lungojs/lungojskitchensink21.apk 
(Wrapped with trigger.io)

**Comment by soyjavi** [comment]
Solved in 2.2 (lungo.brownie)
