### ISSUE TITLE
Action Sheet?

### ISSUE THREAD

**Issue by jashsayani** [tapquo/Lungo.js#158]
I was wondering if there is a UIActionSheet alternative view or a similar view in Lungo. I did not find it in the kitchen sink, are there plans of adding such a view?

**Comment by soyjavi** [comment]
You can use Lungo.Notification http://lungo.tapquo.com/howto/notification/

**Comment by aaronksaunders** [comment]
how can you do an action sheet with this? Action sheet has multiple options for the user to choose from... notifications do not; unless i am missing something
