### ISSUE TITLE
Text color on Aside bar

### ISSUE THREAD

**Issue by davidtavarez** [tapquo/Lungo.js#159]
I'm trying to add a button on the aside bar, but the button style is not the same.

I want the text color and icon white/
![asideColorLungo](https://f.cloud.github.com/assets/337107/165120/299fd5ca-791b-11e2-865c-4a3d8449c725.PNG)

**Comment by soyjavi** [comment]
Buttons in aside/article?? I think it isn't a good pattern... use header/footer for that
