### ISSUE TITLE
Focus on desktop?

### ISSUE THREAD

**Issue by marcalj** [tapquo/Lungo.js#16]
Hi, me again :P.
When twitter bootstrap appears, I was used as a base template for a new project (backend webapp).
I'm wondering if you're focus also in a desktop or big-tablet marketplace.

Thanks!

**Comment by soyjavi** [comment]
In the roadmap I have plans to offer LungoJS for Tablet Devices ... I like it to be ready in version 1.1.

**Comment by marcalj** [comment]
Cojonudo! :)
