### ISSUE TITLE
Side panels multiple activation on left to right drag gesture - Lungo 2.1

### ISSUE THREAD

**Issue by alexradulescu** [tapquo/Lungo.js#160]
The latest version of Lungo, 2.1 which brought gestures by default has a small bug. I will try to explain it as good as possible.
The application/website has a main-article, a left side panel( with the future categories) and a right side mini panel( for future facebook, twitter share). 
Sliding from left to right opens the left panel( ok until here), closes it automatically and then opens the right mini panel( all just from one sliding). And after I close the right mini panel. the button used to open the left panel doesn't work anymore.
For a demo please watch this video: www.youtube.com/watch?v=WES2xv2nWKw .
The website is http://alex034e.keaweb.dk/

Thank you

**Comment by soyjavi** [comment]
Check new version of QuoJS (2.3.6) and Lungo (2.2)
