### ISSUE TITLE
Can not run on Ipad3 with large template, Lungo 1.2

### ISSUE THREAD

**Issue by jiangwille** [tapquo/Lungo.js#161]
I've build an app with Lungo version 1.2, but I get a problem on Ipad3 now. The app includes 25 sections,  40 articles, and the template file has 2700 lines, file size 109kb, it works nice on ipad2, but it cannot run on ipad3, Safari  will crash after the app load. I think because of ipad3's retina display need much more memory on showing such a large html file. My resolvent, separate the template file into 2 file, looks like two apps. Anyone has good idea for this problem?

**Comment by soyjavi** [comment]
v1.2 it's deprecated .. please update for stable version 2.1
