### ISSUE TITLE
pull to refresh with extended header

### ISSUE THREAD

**Issue by cytec** [tapquo/Lungo.js#162]
if i use the extended headers with the qroupbar and an pull to refresh, the pull to refresh position is wrong, it gets overlayed by the groupbar...

![Bildschirmfoto 2013-02-21 um 12 58 24](https://f.cloud.github.com/assets/1104903/180028/0b0bce10-7c1e-11e2-8793-581cd831ac46.png)

**Comment by soyjavi** [comment]
In Lungo 2.2 it's fixed :)
