### ISSUE TITLE
monocle template example

### ISSUE THREAD

**Issue by cytec** [tapquo/Lungo.js#163]
is there an example on how to use monocle templateing in lungo 2.1?

**Comment by soyjavi** [comment]
What do you need?

**Comment by cytec** [comment]
just a basic example on how to create and render templates in lungo.js

currently im parsing json and appending pure html, would love to use mustache templates inside of lungo for my data.

But i cant find any examples for that

**Comment by rodrigobarona** [comment]
Soyjavi makes a hangout with a preview of that but it is not update. You can see here http://youtu.be/gFATYusqPM0 (Spanish version)

But I like to see and update example too

**Comment by cytec** [comment]
yeah i know that hangout video, and there is a different one in spanish... on vimeo i think.

sadly i dont understand spanish, an english version would be nice :)

**Comment by endareceo** [comment]
Big second, I really like what I am seeing with Lungo.js but it is really lacking a template example!

**Comment by cytec** [comment]
any news on this one?

**Comment by soyjavi** [comment]
This wiki it's for Lungo exclusively
