### ISSUE TITLE
data-async load event

### ISSUE THREAD

**Issue by ismaserrano** [tapquo/Lungo.js#164]
First:

Lungo.init({
            name: 'Hello World',
            version: '1.0',
            resources: ['app/sections/section2.html']
        });

When I preload an html, and I have:

Lungo.Events.init({
    'load section#section2': App.foo
});

All works fine.
But when I load the section2.html with 'data-async':

< a href="#section2" data-router="section" data-async="app/sections/section2.html">

Nothing happens (by the way, it's a normal javascript behavior). Then, how I trigger load event? Thanks!

**Comment by ismaserrano** [comment]
Well, I found a solution, editing 'lungo.js', @soyjavi tell me if is correct way...
Add an 'onload' attribute in the '< a />' mark.

< a href="#section2" data-router="section" data-async="app/sections/section2.html" onload="App.foo();">

And, in 'lungo.js', after 'e.Notification.hide()' of the 'async' load:

,e.bind(eval(t.attr('onload')))

Execute 'onload' attribute when #section2 is loaded.

**Comment by soyjavi** [comment]
better if you load/unload event for a <section> element >>

$$("section#id").on("load")  

## 

Javi
Enviado con Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by ismaserrano** [comment]
Yeah! That is the correct way and I had been testing too with QuoJS syntax, but only works when html preload with resources in 'Lungo.init' (first point of the issue), not working for async loading with 'data-async' attribute, at least in my testings.

**Comment by kinhunt** [comment]
I ran into the same problem. Needs to execute some js after async loaded. Any solution yet?
