### ISSUE TITLE
data-transition 'pop & flow' not working

### ISSUE THREAD

**Issue by ismaserrano** [tapquo/Lungo.js#165]
If data-transition is different to 'slide', section not disappears completely and remains in the background. LungoJS version 2.1.

**Comment by soyjavi** [comment]
Device??? In advance ... this data-transition will be dissapear in Lungo.Brownie version

**Comment by ismaserrano** [comment]
iPhone 4. Well... but is Brownie version, dissapears in 2.2? What transitions are available in next version?
