### ISSUE TITLE
Lungo.Notification buttons use <a> tag instead of a <button> tag

### ISSUE THREAD

**Issue by 0xjjpa** [tapquo/Lungo.js#166]
Since when we use Lungo notifications we are not navigating to anywhere but using a callback, a better semantic tag would be <button>. In the worst case, Lungo could use a href="javascript:void(0)" instead of href="#". I know you are proxying the mousedown even with quo, but if anyone tries to route anything outside of that, it's quite hard.

**Comment by soyjavi** [comment]
In lungo 2.2 it's fixed :)

**Comment by 0xjjpa** [comment]
Gracias, saludos.

**Comment by rickkln** [comment]
When is 2.2 coming out?

**Comment by rickkln** [comment]
Never mind, found a post where you say "May" in the Google group.
