### ISSUE TITLE
Scrolling aside background or page header leds to scrolling all the page

### ISSUE THREAD

**Issue by abrahammartin** [tapquo/Lungo.js#167]
![asidescroll](https://f.cloud.github.com/assets/1429691/228023/bc3b597c-8672-11e2-80a2-2fd8b569a020.png)

It is pretended to work like this? It looks strange when the header scrolls down.

Cheers.

**Comment by ismaserrano** [comment]
Prevent bounce or scrolling with XCode. If you use PhoneGap, edit config.xml file and type <pre>< preference name="UIWebViewBounce" value="false" /></pre>
In XCode editing 'UIWebViewBounce' property.

**Comment by abrahammartin** [comment]
thanks @ismaserrano !!
