### ISSUE TITLE
Vector Graphics not showing on IOS

### ISSUE THREAD

**Issue by jimwinchell** [tapquo/Lungo.js#17]
Hello,

Just found Lungo.js this morning...this looks pretty cool.  Just loaded things up a started playing with it and I noticed that the vector graphics are not showing up in my application.  For instance, when I set the 'data-icon' to 'home', all that displays is the letter H rather than the house graphic.  I am testing on an Apple iPhone 3GS with IOS 4.x.  Can you tell me what I am doing wrong?

**Comment by mateosantosdev** [comment]
could you paste your code ?

**Comment by jimwinchell** [comment]
<!doctype html>
<html manifest="index.appcache">
<head>
    <meta charset="utf-8">
    <title>HCP Mobile</title>
    <meta name="description" content="">
    <meta name="author" content="Javier Jiménez Villar (@soyjavi)">
    
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta http-equiv="cleartype" content="on">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/images/icon@2x.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/images/icon-72.png">
    <link rel="apple-touch-icon-precomposed" href="assets/images/icon.png">
    <link rel="apple-touch-startup-image" href="assets/images/default.png">
    
    <link rel="stylesheet" href="./lungo.js/lungo-1.0.1.min.css">
    <link rel="stylesheet" href="./lungo.js/lungo.theme.default.css">
</head> 

<body class="app">
    
    <section id="main">
        <header data-title="Hort Couture® Product Catalog"></header>

```
    <article id="main_article1">
        <scroll id="main_article1_scroll">
        Hort Couture is dedicated to the local, independent retailer and grower. No other brand can say that. We are bringing exciting new plants and ideas to the market that are getting the attention of consumers across North America.
```

<br><br>
We have 28 new varieties in our Avant Garde Annuals for 2012. They represent the finest breeding from leading companies around the world. Our exhaustive search and professional evaluation & trialing will give you the confidence that our varieties are going to be successful not only in your greenhouse but also in your customer's garden.
<br><br>
We have two new series for 2012 that we are really proud to bring to the market. Bacopa BOUTIQUE™ is a stunning new Bacopa with rich eyezones in the flowers that have great appeal and the second series is our new Coleus UNDER THE SEA™ with fun, crustacean type foliage are going to be a big hit with growers and retailers everywhere.
<br><br>
<strong>Help us make the independent channel stronger in 2012!</strong>
</scroll>
        </article>

```
    <footer class="toolbar">
        <nav>
            <a href="#avantgardeannuals" data-target="section" style="font-size:11px;">Annuals</a>
            <a href="#culinarycouture" data-target="section" style="font-size:11px;">Culinary</a>
            <a href="#hortcoutureseed" data-target="section" style="font-size:11px;">Seed</a>
            <a href="#retailandmerchandising" data-target="section" style="font-size:11px;">Retail</a>
            <a href="#runwayreadgrasses" data-target="section" style="font-size:11px;">Grasses</a>
            <a href="#sunnysucculents" data-target="section" style="font-size:11px;">Succulents</a>
        </nav>
    </footer>
</section>

<section id="avantgardeannuals">
    <header data-back="home blue"></header>
    <!-- content -->
    Avant Garde Annuals
</section>

<section id="culinarycouture">
    <header data-back="home blue"></header>
    <!-- content -->
    Culinary Couture
</section>

<section id="hortcoutureseed">
    <header data-back="home blue"></header>
    <!-- content -->
    Hort Couture® Seed
</section>

<section id="hortcoutureseed">
    <header data-back="home blue"></header>
    <!-- content -->
    Hort Couture® Seed
</section>

<section id="retailandmerchandising">
    <header data-back="home blue"></header>
    <!-- content -->
    Retail and Merchandising
</section>

<section id="runwayreadygrasses">
    <header data-back="home blue"></header>
    <!-- content -->
    Runway Ready Grasses
</section>

<section id="sunnysucculents">
    <header data-back="home blue"></header>
    <!-- content -->
    Sunny Succulents
</section>

<!-- LungoJS (Production mode) -->
<script src="lungo.js/lungo-1.0.1.packed.js"></script>
<!-- LungoJS - Sandbox App -->    
<script src="app/app.js"></script>
<script src="app/data.js"></script>
<script src="app/events.js"></script>
<script src="app/services.js"></script>
<script src="app/view.js"></script>
```

</body> 
</html>

-----Original Message-----

**Comment by soyjavi** [comment]
Hi,

In iOS 4.1 @font-face it's soported. What version do you use?

**Comment by jimwinchell** [comment]
I  am using 4.1. Should it work?

**Comment by soyjavi** [comment]
Yap :)

2011/11/18 jimwinchell <
reply@reply.github.com

**Comment by jimwinchell** [comment]
It doesn't work. Did I do something wrong in the code I provided?  Do you have any suggestions on how I can find the problem?

Thanks.
