### ISSUE TITLE
Errors in Win8 (tablet and desktop)

### ISSUE THREAD

**Issue by lolohouse** [tapquo/Lungo.js#171]
When it show lungo examples in Win8 (tablet and desktop) , It give console errors:
SCRIPT438: El objeto no acepta la propiedad o el método 'ready' 
quo.js, Línea 4 Carácter 13642
SCRIPT438: El objeto no acepta la propiedad o el método 'append' 
lungo.js, Línea 4 Carácter 5199
SCRIPT5007: No se puede obtener la propiedad 'load' de referencia nula o sin definir 
lungo.js, Línea 4 Carácter 3832
SCRIPT5007: No se puede obtener la propiedad 'indexOf' de referencia nula o sin definir 
lungo.js, Línea 4 Carácter 3398
SCRIPT438: El objeto no acepta la propiedad o el método 'on' 
events.touch.js, Línea 7 Carácter 5
SCRIPT445: El objeto no acepta esta acción 
events.pull.js, Línea 1 Carácter 1
SCRIPT438: El objeto no acepta la propiedad o el método 'Carousel' 
events.carousel.js, Línea 1 Carácter 1
SCRIPT5007: No se puede obtener la propiedad 'indexOf' de referencia nula o sin definir 
lungo.js, Línea 4 Carácter 3398
SCRIPT438: El objeto no acepta la propiedad o el método 'tap' 
events.themeroller.js, Línea 1 Carácter 1

**Comment by soyjavi** [comment]
WIndows 8 it's not supported ... "only"
iOS, Android, Blackberry & Firefox OS
