### ISSUE TITLE
Lungo 2.1 + Icenium (PhoneGap)

### ISSUE THREAD

**Issue by Jeelig** [tapquo/Lungo.js#179]
Hi,

I use Lungo with <a href="http://www.icenium.com/">Icenium</a>.
Icenium helps me to build native iOS/Android on my devices.
<a href="http://www.m0si.com/mylungo">Here</a>'s my code. It works great on Android when I launch to the WebSite from URL.

The problem is when I build it in icenium for my Galaxy S3. Nothing works!
Scroll, side menu ...

I've seen in one of the closed issues that IT could be a bad phonegap configuration but no real reason why it doesn't work and actually I did no special configuration.

On iPhone, no problem. Works great!

Can someone help me with this issue?

**Comment by batuhan** [comment]
You can use a remote JS debugger to see console errors, maybe?

http://jsconsole.com can you help with that, if I remember correctly .

**Comment by jomarmen** [comment]
Did you try https://build.phonegap.com/?

**Comment by Jeelig** [comment]
I tried the <a href="http://build.phonegap.com">PhoneGap Build</a> service and it works!
I can't figure out why it didn't work but thank you Jomarmen.
I will close the issue but I would go to bed a <i>Wiser Man</i> if I could know what exactly the problem is.
Any idea?

**Comment by Jeelig** [comment]
Issue created on the Icenium Project.
Thanks Guys

**Comment by stzokev** [comment]
Just for reference, see the resolution to the issue Jeelig created: http://www.icenium.com/community/forums/permalink/NOirRanxMECQzUD73Bv2cw

**Comment by Jeelig** [comment]
I tried it, it seem to solve most of the problem. But still the left side menu is not revealed after click
