### ISSUE TITLE
Android 3.2 testing

### ISSUE THREAD

**Issue by surfjedi** [tapquo/Lungo.js#180]
I have been testing out lungo in adroid 3,2 and 2.3.  It seems to have issues like laggin and sticking with the asides in both on your example.  Lingo looks promising but imseeing so many animation issues.

And better examples?

**Comment by soyjavi** [comment]
Lagging it's a navigator problem.. you can remove data-transition property in sections for a better perfomance in android devices

**Comment by dallasbpeters** [comment]
Can you expound on this a bit more? Wouldn't removing this remove the transition altogether?

**Comment by kinhunt** [comment]
section cannot go back without the data-transition property
