### ISSUE TITLE
trying out of the box examples not working on desktop

### ISSUE THREAD

**Issue by surfjedi** [tapquo/Lungo.js#181]
Im tyring the examples out of the box from zip downloads and git repo. But all are giving me:

Error:

Uncaught TypeError: Object #<Object> has no method 'touch' lungo.debug.js:1806
Lungo.Boot.Events.init lungo.debug.js:1806
Lungo.init lungo.debug.js:592
(anonymous function)

Can any one explain?

**Comment by batuhan** [comment]
I think this repo contains brownie version, which is unstable.

You can download the stable version 2.1 from the website.

Or you can try bower install: "bower install lungo quojs lungo.icon"

Or, for the unstable (but working) version of the brownie, "bower insltall
lungo.brownie quojs lungo.icon"

## Note: I'm have no relation to TapQuo, I'm just a user.

Batuhan Icoz http://batu.me/1
*
*
_General disclaimer, other ways to contact and detailed information of me
can be found here http://batu.me/1._

**Comment by surfjedi** [comment]
Thanks, I'll give that a go. I appreciate the help
—
