### ISSUE TITLE
Icon modifier classes conflicting with other classes

### ISSUE THREAD

**Issue by efoken** [tapquo/Lungo.js#182]
For example `.tag` conflicts with `.icon.tag`, so that the icon gets the style of tags too. Besides that, if someone defines new classes in his app stylesheet, he has to be careful not to change some icons appearance.

So maybe the icon classes should be something like `.icon-tag` (using a minus). To style icons globally we can use the attribute selector `[class^="icon-"]` like original FontAwesome does.

**Comment by soyjavi** [comment]
Solved in coming soon version 2.2
