### ISSUE TITLE
Latest (lungo.brownie) build not working on iPad

### ISSUE THREAD

**Issue by cayasso** [tapquo/Lungo.js#183]
Just downloaded and build the latest lungo version (lungo.brownie) but it doesn't work on iPad, I only get a the aside menu but a the rest is all black, I think it could be an issue with media queries, I whenever I disable the tablet media queries it no longer show black.

The other issue is that the touch event to open aside is not working, it looks like the it is not recognizing the touch event on the top left button.

Everything work fine on iPhone devices.

I hope you can point me to some quick fix, I really need to get this working :(

Thanks!!

JB

**Comment by batuhan** [comment]
I had the same problem, I fixed it by adding some css. Check #178. :)

**Comment by cayasso** [comment]
Awesome!
Thank you @batuhanicoz this is great help, i got it working now.
Question: after that change did you had issues with scrolling or touch events(on iPad)?

**Comment by soyjavi** [comment]
Current (and suported) version is 2.1 ... Lungo.Brownie it's only for tapquo developers

**Comment by cayasso** [comment]
But you already have it in the master branch!

**Comment by soyjavi** [comment]
Stable Version 2.1:

https://github.com/TapQuo/package-lungo

**Comment by cayasso** [comment]
Ok so how do I get version 2.1 without it minified? I would like to build it my self.

**Comment by batuhan** [comment]
try this https://github.com/TapQuo/Lungo.js/archive/b6c72b3fd29e93fe9ea28bf626cc9dff78ba52d9.zip

**Comment by cayasso** [comment]
Awesome thank you again @batuhanicoz , I will try that!!!

**Comment by soyjavi** [comment]
+1 @batuhanicoz :)
