### ISSUE TITLE
i want to add a splash page when app begins

### ISSUE THREAD

**Issue by colorlife2012** [tapquo/Lungo.js#185]
i want to defer to "static/sections/splash", but my try always failed, how to do this? thanks for any suggestion.

**Comment by rkorobeynikov** [comment]
You should to use link tag with rel="apple-touch-startup-image".
Read the following links:
http://stackoverflow.com/questions/3707509/startup-image-in-webapp-for-retina-display
http://stackoverflow.com/questions/4687698/mulitple-apple-touch-startup-image-resolutions-for-ios-web-app-esp-for-ipad

**Comment by colorlife2012** [comment]
thank u!!
