### ISSUE TITLE
add transitions to use in the articles

### ISSUE THREAD

**Issue by tinchoz49** [tapquo/Lungo.js#186]

**Comment by batuhan** [comment]
this would be awesome. +1

**Comment by soyjavi** [comment]
Sorry, but I think it's better no transitions (more perfomance)

**Comment by o0x2a** [comment]
If you are concerned about performance, you know that css3 transitions are hardware accelerated. Today, all smartphone are shipped with a decent GPU. It means transitions using css3 consume little to _none_ cpu cycles. It would great if you could let the user decide whether to use transition or not. Few month ago, I choose Lungo.js among my other 10 choices, I really liked it. It was fast and just enough, my only problem was transition on articles, and it was the only reason it didn't suit my project.

**Comment by cytec** [comment]
definetively give a +1 here :+1:
