### ISSUE TITLE
error in the callback using Notification.error

### ISSUE THREAD

**Issue by tinchoz49** [tapquo/Lungo.js#187]
when you define a Notification.error with a callback function (afterNotification) this function is only execute when the notification is hidden by the timeout, but if you hide the notification by a click the callback wait for the timeout, so is not correct that.

**Comment by soyjavi** [comment]
Solved in 2.2 (released may 2013)

**Comment by kurian86** [comment]
Hola, esto aun sigue pasando, si no le pasas un timeout no se ejecuta el callback.

**Comment by kurian86** [comment]
Esto me ha funcionado a mi, por si alguien lo necesita

``` coffeescript
_hide = (seconds, callback) ->
    if seconds? and seconds > 0
      setTimeout (=>
        if callback
          callback.call undefined, callback
        else
          do hide
      ), seconds * 1000
    else
      if callback
        lng.dom(SELECTOR.BODY).off "tap", SELECTOR.WINDOW_CLOSABLE
        lng.dom(SELECTOR.WINDOW_CLOSABLE).tap (event) ->
          callback?.call undefined, callback
          hide()
```
