### ISSUE TITLE
Problem with select (websql)

### ISSUE THREAD

**Issue by mateosantosdev** [tapquo/Lungo.js#19]
Hi,

Im playing with WebSQL features and I have a problem, I cannot get the results...

This is my code:

``` javascript
var selectTask = function(data){

        var datos = [];

        lng.Data.Sql.select('tasks', {done: 0}, function(result){

            for (var i=0; i < result.length; i++) {
                datos.push({
                    id: result[i].id,
                    name: result[i].name,
                    description: result[i].description
                });
            }

            lng.Core.log(1, "Antes: " + datos.length);

        });

        lng.Core.log(1, "Despues: " + datos.length);

        return datos;
    };
```

All I get is: 
Antes: 2
Despues: 0

Any idea ?

Thanks!

**Comment by soyjavi** [comment]
WebSQL is a async API... your example code it's async :).

Other example:

```
var selectTask = function(data){
    lng.Data.Sql.select('tasks', {done: 0}, function(result) {
        //Call to a method (to continue the flow)
        read_tasks(result);
    });
};

var read_tasks = function(data){
    for (var i=0; i < data.length; i++) {
        datos.push({
            id: data[i].id,
            name: data[i].name,
            description: data[i].description
        });
    }
    lng.Core.log(1, "Antes: " + datos.length);
};
```

**Comment by kurnajata** [comment]
Hola Javi,
En una prueba que estoy haciendo, también me sale mal con el código que has puesto.Al final (ojo, que soy nuevo!!) he hecho como lo tienes en Template.Bindings:

<pre>var data_type = lng.Core.toType(result);
    if (data_type === 'array') {
        for (var i=0; i &lt; result.length;i++){    
            sumatorio += result[i].NombreCampo; 
        }    
    } else if (data_type === 'object') {
        sumatorio += result.NombreCampo;        
}</pre>


Si es un sólo registro Data.Sql devuelve un object.

Saludos,

**Lungojs 1.0.3**

**Comment by soyjavi** [comment]
Eso es si solo es un reistro devuelve un object ;) para una mejor perfomance

Enviado desde mi iPad

El 13/12/2011, a las 21:53, kurnajata
reply@reply.github.com
escribió:

**Comment by colorlife2012** [comment]
Cound i use lungo like following?

```
 var result =  lng.Data.Sql.select('tasks', {done: 0} );
 or  
 var result =  lng.Data.Sql.select('tasks', {done: 0} ,'abc');


 i want the result, 
 but select doesnt give anything back,  only pass data to abc, but abc cant return anything.
 something wrong with my use? 
 thanks for helping.
```
