### ISSUE TITLE
Aside issue in Android 4.0.3

### ISSUE THREAD

**Issue by voppe** [tapquo/Lungo.js#190]
I'm using Lungo 2.1 and I've been trying to open an aside by using a button placed in the header's left side.
It works like a charm on Android 2.3.3, 4.0.4 and 4.2.1, but refuses to register the tap when in portrait mode.
It does work when in landscape mode though, although only once, meaning that you can toggle it on and off after which it goes back to not working. Switching to portrait mode and back to landscape resets this behavior. 
I've tested it with two different 4.0.3 Galaxy S2 and it does not work, while with a 4.0.4 S2 it has no problem. I can also replicate the issue in a 4.0.3 AVD, whereas with other versions AVDs it works.

**Comment by miguelreng** [comment]
are now in my code of lungojs, I also feel the same help me

**Comment by soyjavi** [comment]
Check v2.2
