### ISSUE TITLE
Swipe to open aside doesn't work on google nexus4 with android 4.2.2

### ISSUE THREAD

**Issue by tmpduarte** [tapquo/Lungo.js#191]
I tried to swipe to open the aside on http://lungo.tapquo.com/example/index.html and some problems occurred:

1 - the aside doesn't open completely
2 - after swiping the click to open the aside doesn't work anymore

ps.: I was using the native browser of a google nexus4 with android 4.2.2, everything works fine on safari on iPhone4 with ios6.1.3

**Comment by soyjavi** [comment]
We've detected that in native browser of 4.2+ there is a problem with TouchCancel and TouchEnd events (necesary for QuoJS swipe events).

**Comment by juanbermudez** [comment]
Javi, is there any fix for making it work on 4.2+ ?  I ran into the same issue. Also scrolling a simple list seems to be nowhere close to how it works on other devices. Barely moves sometimes when you try to scroll a list on the Demo
