### ISSUE TITLE
Kitchen Sink Does Not Work

### ISSUE THREAD

**Issue by calendee** [tapquo/Lungo.js#194]
I've cloned the entire Lungo.js framework.  I'm trying to load the "examples" or "Kitchen Sink" in the browser on the desktop.

All is get is : 
    `Uncaught TypeError: Object #<Object> has no method 'touch'`

The error is in lungo.debug.js:1806

The application does not load in Safari on iOS 6 either.

Suggestions?

**Comment by i8ramin** [comment]
Same here. Tried replacing the lungo.js and quo.js files with the latest pulled in via bower, but I get different errors. Any help getting the "kitchen sink" example to work would be greatly appreciated.

**Comment by emmerich** [comment]
I get this error as well. It also seems as though the examples are completely missing some components such as `Lungo.Data`, which is an empty object.

**Comment by voppe** [comment]
Same. I replaced the .touch and .tap function calls with .on('touch', and .on('tap', but no luck either.

**Comment by calendee** [comment]
I was never able to get the examples from the GitHub examples to work.  Instead, I downloaded the Zip example on the Lungo website.  Everything works from there.

**Comment by Arota** [comment]
I replaced <code>.touch(</code> by <code>.tap(</code> and i it fixed it :D

**Comment by soyjavi** [comment]
Update your QuoJS submodule (git)
