### ISSUE TITLE
Function callback for Notification.hide

### ISSUE THREAD

**Issue by nazieb** [tapquo/Lungo.js#195]
Hi,

I just want to give idea about giving a callback function as parameter for Lungo.Notification.hide function.

Recently I need to call some AJAX request after the Notification is hidden, but there's no way to do it. So all I need to do is call another setTimeout to check whether the notification is already hidden.

Thank you

**Comment by aesedepece** [comment]
There is no need for that.

You can attach a callback that runs when notification hides by adding it when calling `Lungo.Notification.show()`:

``` javascript
Lungo.Notification.show(title, icon, lifetime, callback);
```

It is explained in the reference:
http://lungo.tapquo.com/howto/notification/

**Comment by nazieb** [comment]
Ah, I've missed that. Thanks for pointing out
