### ISSUE TITLE
Bad query when using Lungo.Data.Sql.select with callback but no search condition

### ISSUE THREAD

**Issue by zeopix** [tapquo/Lungo.js#197]
I'm executing LungoJS on Chrome
I've tried to use
Lungo.Data.Sql.select('collection',function(data){
     console.log(data)
});

In the console trace i see the prepared query: 
lng.Data.Sql >> SELECT \* FROM collection WHERE

But the correct one should be
lng.Data.Sql >> SELECT \* FROM collection

I've been looking at the code in this repository, but I failed to find where the function Sql.Select  is defined.

Can you tell me how to proceed to solve this?

Thanks at all

**Comment by soyjavi** [comment]
I'm sorry but Lungo.Data.Sql is deprecated (v2.2)
