### ISSUE TITLE
issue with a tag

### ISSUE THREAD

**Issue by waltermazzariol** [tapquo/Lungo.js#204]
I am developing an app with this framework the link to see it is http://formateate.com.ve/unimet this is my grade project for he university.

now the problem is when i open the "calendario" tap on the menu automatically open de second link on the page, this problem occur when i open from safari o chrome on my iphone.

i think this could be a css problem but i did not find it :/

thank for any help, sorry for my english

**Comment by soyjavi** [comment]
The problem it's in your webapp, not in Lungo... I think you should use styled buttons (with lungo)
