### ISSUE TITLE
Aside Navigation issue

### ISSUE THREAD

**Issue by craimasjien** [tapquo/Lungo.js#205]
Hi guys!

I'm building this cross-platform application in Lungo, and I'm experiencing a strange visual glitch which I frankly can't place.
Whenever I open the aside, and select another section via the aside, the aside closes and the currently open page should switch to the newly selected section and designated article.
However, the page changes but the old page will be frozen above it for a fraction of a second and just disappear. this is obviously not the UX i want to create here. (see screenshot)

The way I change articles from the aside is:

Lungo.dom('[data-target=news-articles]').tap(function(){
     //Lungo.Router.article("news-section", "news-article");
     Lungo.Router.section("#news-section");
     Lungo.Router.aside("main", "features");
});

This produces the bug. It's happening on both section+articles combinations that are inside the index.html as section+articles that are in a different Html file. 
Am I doing the navigation the right way? Or is this a bug?

![ios simulator screen shot may 28 2013 4 21 29 pm copy](https://f.cloud.github.com/assets/1733692/572813/4ff05476-c7a3-11e2-9e5a-f2129ea4cf5b.png)

**Comment by soyjavi** [comment]
I think it's a bug, but for your information we're working in a new router for Lungo Brownie (2.2)
