### ISSUE TITLE
No package.json to build the project?

### ISSUE THREAD

**Issue by i8ramin** [tapquo/Lungo.js#209]
Hi, I am trying to clone and build this project, but there is no package.json file to run npm install against. Are there instructions somewhere on how to compile these files down to JS? I'm interested in contributing to the project, but need some assistance getting it setup. I will try to put together a package.json file of my own, but if you have one already, can you please commit it to source control? Thank you.

**Comment by soyjavi** [comment]
The package.json it's in lungo.package project

https://github.com/tapquo/package-lungo
