### ISSUE TITLE
Git submodule ini failing

### ISSUE THREAD

**Issue by i8ramin** [tapquo/Lungo.js#210]
Wondering if anyone else has had issues running git submodule init/update on this project? I get the following error:

```
› git submodule update
Cloning into 'packages/lungo'...
fatal: https://github.com/TapQuo/package-lungo/info/refs?service=git-upload-pack not
found: did you run git update-server-info on the server?
Clone of 'https://github.com/TapQuo/package-lungo' into submodule path 'packages/lungo'     
failed
```

Also, some instructions on how to help contribute to this project would be great. What git commands to run. How to compile the packages. What tools are needed (npm, bower, etc.)

Thanks

**Comment by hanno-jonlay** [comment]
Hey @i8ramin - I got these problems yesterday, but by the evening they seemed to be ok. Not sure if one of the recent commits fixed the submodule problems, perhaps.

**Comment by i8ramin** [comment]
I'll give it a try when I get home. Have you had any luck building the packages using Grunt? There doesn't seem to be a package.json file or anything. 
—

**Comment by hanno-jonlay** [comment]
Yeah, I've seen the same problems. There's another open issue here discussing that, but doesn't look like it has a solution yet, and I couldn't see a package.json in the repo history either. I hear that downloading the compiled zip from the main lungo marketing site might be the best option, but of course, it'd be much better if we could keep the original source and coffee files.

Planning to have a look at creating a package.json but I only started using Grunt a month ago so I might struggle :wink:

**Comment by soyjavi** [comment]
Check if your gitmodule package urls it's https://github.com/tapquo/....

**Comment by soyjavi** [comment]
Steps:
- fork project
- npm install
- git submodule update (or init)
- grunt
