### ISSUE TITLE
First click notify response error

### ISSUE THREAD

**Issue by dome** [tapquo/Lungo.js#217]
In last commit i got problem in notify section. when i click (any botton) nothing happen. and it's work in second click. and sometime all click no reponse.

**Comment by soyjavi** [comment]
Click??? you need subscribe to touch event

**Comment by dome** [comment]
in Lungo.Notification.coffee it's work when i remark some line.

 _show = (html, stylesheet, block = true) ->
    ##if block then _el.removeClass "push" else _el.addClass "push"

```
##unless _window.hasClass("show")
_el.addClass("show")
##else
##  _window.removeClass STYLE.SHOW
```

**Comment by mylittleplanet-apps** [comment]
@soyjavi I'm sorry but the Lungo.Notification doesn't work properly , even in http://lungo.tapquo.com/demo/# . It works only one the second click/touch or sometime not. Will you fix it soon ? or is there another way to show notification properly ?

**Comment by enaros** [comment]
I had run into the same problem and came up with the same solution @dome is proposing, and it works

**Comment by mylittleplanet-apps** [comment]
@enaros Thanks for your response but I'm new to LungoJS .And I've just imported the examples folder in my project(https://github.com/tapquo/Lungo.js/tree/master/example). How can I import stuff like Lungo.Notification.coffee file ? :s

**Comment by enaros** [comment]
@timawl You are welcome. You should:
1. Clone https://github.com/tapquo/Lungo.js.git
2. It uses Grunt for generating and compiling stuff like coffeescript, so you need to use it to get the compiled Lungo*.js files

If you dont know what am I talking about, there is a quick and dirty solution for you:
1. Make sure you are using Lungo.debug.js version (the readable one)
2. Find the definition of Lungo.Notification (tip: search for "Lungo.Notification =")
3. Inside there find the method _show = function(html, stylesheet, block)
4. it should look now like this:

``` javascript
    _show = function(html, stylesheet, block) {
      if (block == null) {
        block = true;
      }
      if (block) {
        _el.removeClass("push");
      } else {
        _el.addClass("push");
      }
      // if (!_window.hasClass("show")) {
        _window.removeClass("show");
        _el.addClass("show");
      // } else {
        // _window.removeClass(STYLE.SHOW);
      // }
      return setTimeout((function() {
        _window.html(html);
        return _window.attr("class", "window " + stylesheet + " show");
      }), TRANSITION.DURATION / 2);
    };
```

The reason it was working with double clicks is that there is a timeout and then if you click fast enough the css classes change and the notification is displayed.

Hope it helps

**Comment by mylittleplanet-apps** [comment]
Thanks you very much. I will try it this afternoon :D

**Comment by mylittleplanet-apps** [comment]
@enaros it works great ! Thanks a lot

**Comment by enaros** [comment]
you are welcome, btw @soyjavi, commenting those lines solve the problem but
I am not sure if that is the "right" fix for this...

**Comment by mylittleplanet-apps** [comment]
@enaros Can you please check my new issue (https://github.com/tapquo/Lungo.js/issues/246) . Thanks

**Comment by enaros** [comment]
no idea, I can't help you without seeing what you have done, and I have never used icenium. Have you tried phonegap instead?

**Comment by mylittleplanet-apps** [comment]
I 've just copied the example sample code and compile it with Icenium. No I haven't try phonegap yet but I prefer to stay with Icenium. I'll try to find a solution , maybe implement Iscroll ?

**Comment by mylittleplanet-apps** [comment]
@enaros I simply delete "class=drag" in <section> and it works ! :D

**Comment by alexpchung** [comment]
Thank you enaros.  I could not find the lungo.debug.js file, so I edited the unreadable lungo.js and it fixed the notification problem.

**Comment by saniyusuf** [comment]
I can confirm this fix works. :+1: 
@alexpchung you can find the debug file here : https://github.com/soyjavi/lungo.brownie/blob/master/lungo.debug.js
