### ISSUE TITLE
Swipe left on ios

### ISSUE THREAD

**Issue by eatfrog** [tapquo/Lungo.js#22]
On IOS devices it is possible to swipe left to see other sections that should not be available to the user before clicking a button. It is possible i have misunderstood something, but since there is so little documentation and no forum i'm making an issue out of it.

On android it works just fine.

How to reproduce:
Make several sections, after loading the first, swipe left.

**Comment by soyjavi** [comment]
I know ... in release 1.0.2 will be corrected :)
