### ISSUE TITLE
How to pass data between articles

### ISSUE THREAD

**Issue by miguelsanchezvigo** [tapquo/Lungo.js#220]
Hi, I have a section with two articles, first article is a list where display lastest news, second article is detail of news. My first way is load news content on second article on click (or tap) on first article list. For do this, I need pass news id or some data that identifier news to second article. Actually in first article I have a list with <a href="#second-article"> and load event binding to #second-article, I try bind click event to li or <a> to pass data but don't works and I think that is not best way. What is the best way to do this?

Thanks!

Como no brillo por mi ingles, voy a traducir un poco lo que necesitaba. Tengo una section con dos article uno muestra una lista con las ultimas noticias y otro muestra el detalle de la noticia. La idea es hacer click en un elemento de la lista del primer articulo y que se muestre el segundo article con el contenido, titulo... Pero para esto necesito pasar un parametro que identifique cual es la noticia que quiero recuperar. Ahora mismo tengo un trigger on load cuando se carga el segundo articulo e intentaba modificar una variable con el identificador de la noticia al hacer click en la fila de la lista o en el enlace, para que cuando se hiciese on load, se recupere la variable y busque el articulo que corresponda, pero no soy capaz de que funcione y me da que no es la mejor forma de plantearlo. Como sería la mejor forma de hacer esto?

Muchas gracias!

Pd. Es increíble vuestro trabajo. Enhorabuena

**Comment by justindomingue** [comment]
Check out Monocle by Tapquo. Or use a javascript route library.

**Comment by saniyusuf** [comment]
Is There Is Clear Way To DO This Yet Using Query String Parameters or something similar. Currently i just Use A global variable to set my variable and it works but I think Query String Parameter Is The Best.
ANy Help ?

**Comment by soyjavi** [comment]
It isn't Lungo Responsibility, use a MVC framework.
