### ISSUE TITLE
data-icon css in header should be similar to data-back

### ISSUE THREAD

**Issue by pcambra** [tapquo/Lungo.js#23]
Hi

Not sure if it's the desired behavior, but if you use data-icon in a header tag, you get the icon, but without all the 'cool' css applied so it's very small by default, unlike you (I) would expect. If you place an anchor with data-back, icon looks good.

**Comment by soyjavi** [comment]
Could you give an example?

Thanks

**Comment by pcambra** [comment]
Example:
<.header data-title="test title" data-icon="home blue" data-back="home pink">
Result:
https://skitch.com/pcambra/gk761/test-title

**Comment by soyjavi** [comment]
estas mezclando conceptos... data-icon no se puede asociar a un header.

2011/11/23 Pedro <
reply@reply.github.com

**Comment by soyjavi** [comment]
You are mixing concepts, data-icon attribute is used in items <a>
