### ISSUE TITLE
data-async don´t run

### ISSUE THREAD

**Issue by Jacen** [tapquo/Lungo.js#237]
When I tap in "go to section", it would go to ppal.html y show "main" section, but it shows "main section"?? in index.html page
index.html#main

here is my code
https://github.com/Jacen/PruebasLungo

**Comment by Jacen** [comment]
the error 
XMLHttpRequest cannot load file:///L:/PROYECTOS/HTML/PruebasLungo/ppal.html. Cross origin requests are only supported for HTTP quo.js:4
ERROR: Loading resource: ppal.html

**Comment by saniyusuf** [comment]
Similar Problem. Any Luck?

**Comment by soyjavi** [comment]
Cross-Origin >> Try test in a web server :) (or disable your security policies to try a file://...)
