### ISSUE TITLE
Article in template

### ISSUE THREAD

**Issue by eatfrog** [tapquo/Lungo.js#24]
I would like it to be easier to work with articles in templates. In my case i have a section, to which a template outputs a number of articles, and in the footer i'd like to have the navigation to these articles.

I was able to get it to almost work, but it was unnecessarily difficult, and i didn't get it to work on android at all.

Maybe somekind of LUNGO.Refresh() function, that you can call when stuff has happened in the dom that would require lungo to read it again and do its magic?

An example for this case in the documentation would also be nice, since i think its a pretty common scenario, get a bunch of stuff from remote server, swipe left to scroll through them.

**Comment by soyjavi** [comment]
You can call to lng.Boot(); it's easy

**Comment by eatfrog** [comment]
Ah, great. Thanks.

However, this is not a documented function. Also, boot sounds like something you only do once.
