### ISSUE TITLE
Cannot use a button with an icon inside a fieldset.

### ISSUE THREAD

**Issue by rafaelgaldencio** [tapquo/Lungo.js#242]
Print screen, for better understanding.

![outside_fieldset](https://f.cloud.github.com/assets/1440742/826549/77aa4e50-f088-11e2-91c1-a5c09179a13b.png)
Outside fieldset - works fine

![inside_fieldset](https://f.cloud.github.com/assets/1440742/826552/851903ce-f088-11e2-94b2-20564fc93ebe.png)
Inside fieldset - icon goes superman. :)

**Comment by soyjavi** [comment]
Use .display.block classes

**Comment by rafaelgaldencio** [comment]
Didn't see the comment before, but .display.block did the trick. Thanks! Closing the issue.
