### ISSUE TITLE
Lungo Router breaks on device with width > 768px

### ISSUE THREAD

**Issue by justindomingue** [tapquo/Lungo.js#245]
When Lungo is loaded from a device with a width greater than 768px, Lungo seems to break  : 
- Router is not working
- The aside is shown (though according to the CSS files this is the wanted behaviour).

These issues are the only ones I see for now.

**Comment by maxaud** [comment]
See this issue too, sounds related:
https://github.com/tapquo/Lungo.js/issues/214

**Comment by justindomingue** [comment]
It is indeed related. The issue appears on 2.2 in my case.

**Comment by maxaud** [comment]
It should be noted that my screenshot is from 2.2 as well.

**Comment by justindomingue** [comment]
I think this is an urgent issue - it renders LungoJs unusable on all tablet devices!

**Comment by maxaud** [comment]
Agreed. Very sad.

**Comment by florindumitru** [comment]
+1

**Comment by VittorioMobimentum** [comment]
I have the same problem. Also data-view-aside breaks. When clicked it log `Cannot call method 'getAttribute' of undefined` from quojs. Maybe it could help.

**Comment by justindomingue** [comment]
**EDIT** Turned out I had not refreshed the browser - the problem persists.

I found that you can hide the aside on tablet devices by deleting the data-aside attribute of your main section :

From the documentation : 

> In your section if you want view aside automaticaly in Tablet-Apps you need link your aside with data-aside attribute, and you can display/hide with attribute data-view-aside

**Comment by gm-fire** [comment]
After deleting data-aside attribute, class="drag" ineffective.

**Comment by Arota** [comment]
I have kind of the same problem here on Safari & Chrome on the iPhone iOS6.
Nav buttons are not working after first tap.

iPad no problem and Chrome on my mac works just fine.

**Comment by soyjavi** [comment]
Solved in Lungo 2.1.1 (we'll release this version ... this week)

**Comment by justindomingue** [comment]
I am so glad :D keep up the good work!

Wait... 2.1.1? Do you mean 2.2.1?

**Comment by relevantidea** [comment]
Is this already released with a fix for 2.1.1 or 2.2.1? We are experiencing the same issue.

**Comment by justindomingue** [comment]
No :/ Lungo has not been updated in a month!

**Comment by fatihsever** [comment]
I'm using 2.2.1 and I've the same issue. Could you check this please. There is a huge problem on tablets. Thanks.

**Comment by fatihsever** [comment]
I opened same issue #284 because of this issue status is closed.

**Comment by relevantidea** [comment]
Im beginning to wonder if this is abandoned? Do I need to pay for a license to get something fixed?

**Comment by justindomingue** [comment]
@relevantidea I understand your point - I opened this issue 2 moths ago and a fix was supposed to be made 1 month ago... You have three options : 
- Cry and never use Lungo again
- Wait for a fix
- Write the fix

Personaly, I think I'll choose 1 ;-)

**Comment by TheAppCooker** [comment]
Fix :)?

**Comment by webmaster-hm** [comment]
Anyone suggest?

**Comment by smoj** [comment]
Does this help? https://github.com/tapquo/Lungo.js/issues/297#issuecomment-32709859

**Comment by webmaster-hm** [comment]
Fine! But the transitions in landscape mode doesn't working fine. Any 
solution?
