### ISSUE TITLE
Scroll not working when add item to list with append

### ISSUE THREAD

**Issue by florindumitru** [tapquo/Lungo.js#249]
Scroll not working when add item to list with append ... I don't want to use iScroll .. not again so maybe someone fix that.

To Lungojs team - great framework but... still a lot to fix .. and maybe a better support will be great.

thx

**Comment by soyjavi** [comment]
Lungo, since version 2.1, use native scroll via overflow CSS property ... if your device doesn't support this CSS feature you must use a third library such as iScroll
