### ISSUE TITLE
Opening hyperlinks through sidebar

### ISSUE THREAD

**Issue by kkdeep** [tapquo/Lungo.js#252]
Is it possible to open an external/internal link within the app itself?

I have used 

```
    <li data-event='about'><a data-icon='info'>About</a></li>
```

in main.html

& script as

$$('aside#options li[data-event=about]').on('click', function (e) 
{

   window.location  = "about.html"

 Lungo.Router.aside('main', 'social');

});

**Comment by soyjavi** [comment]
sorry but <a> tag should have "href" attribute.
