### ISSUE TITLE
About <nav data-control="groupbar">

### ISSUE THREAD

**Issue by gm-fire** [tapquo/Lungo.js#254]
When <code>< nav data-control="groupbar"></code> inside <code>< a></code> beyond the screen width sliding around when the show could become

example:
<code>< nav data-control="groupbar">
    < a href="#" data-view-article="form-1" data-label="11111" class="active"></a>
    < a href="#" data-view-article="form-2" data-label="22222"></a>
    < a href="#" data-view-article="form-3" data-label="33333"></a>
    < a href="#" data-view-article="form-4" data-label="44444"></a>
    < a href="#" data-view-article="form-5" data-label="55555"></a>
    < a href="#" data-view-article="form-6" data-label="66666"></a>
    < a href="#" data-view-article="form-7" data-label="77777"></a>
    < a href="#" data-view-article="form-8" data-label="88888"></a>
    < a href="#" data-view-article="form-9" data-label="99999"></a>
    < a href="#" data-view-article="form-0" data-label="00000"></a>
    < a href="#" data-view-article="form-a" data-label="aaaaa"></a>
    < a href="#" data-view-article="form-b" data-label="bbbbb"></a>
    < a href="#" data-view-article="form-c" data-label="ccccc"></a>
    < a href="#" data-view-article="form-d" data-label="ddddd"></a>
    < a href="#" data-view-article="form-e" data-label="eeeee"></a>
< /nav></code>

![1](https://f.cloud.github.com/assets/5047482/952440/fb39a7e0-03cd-11e3-85a5-609643f91de0.jpg)

**Comment by soyjavi** [comment]
I'm sorry but it's imposible make a slider in data-control="groupbar" ... maybe in Lungo 3
