### ISSUE TITLE
how to clean data-transition="slide" ? 

### ISSUE THREAD

**Issue by chinahuarvin** [tapquo/Lungo.js#256]
I don't want to have the slide style.but if i don't add this code(data-transition="slide") ,it can not work between sections.

**Comment by chinahuarvin** [comment]
data-transition=""  and data-transition="none"  and move this code can not work.

**Comment by Arota** [comment]
Same problem here, without "slide" it won't work!

**Comment by soyjavi** [comment]
You must create a new animation in CSS and put it's name in data-transition attribute

**Comment by tchavot** [comment]
Could you please give the code to add to the css file in order to create a new animation without any effect?

**Comment by maytis** [comment]
/\* NO TRANSITION */

@-webkit-keyframes none {
  0% {
    opacity:0;
  }

  100% {
    opacity:1;
  }
}

@keyframes none {
  0% {
    opacity:0;
  }

  100% {
    opacity:1;
  }
}

.none {
  -webkit-animation-name: none;
  animation-name: none;
}

/\* USING THE NO ANIMATION */
body[data-device="phone"] > section[data-transition="none"][data-direction="in"]{-webkit-animation-name:none;-moz-animation-name:none;-ms-animation-name:none;-o-animation-name:none;animation-name:none}
body[data-device="phone"] > section[data-transition="none"][data-direction="out"]{-webkit-animation-name:none;-moz-animation-name:none;-ms-animation-name:none;-o-animation-name:none;animation-name:none}
body[data-device="phone"] > section[data-transition="none"][data-direction="back-in"]{z-index:1;-webkit-animation-name:none;-moz-animation-name:none;-ms-animation-name:none;-o-animation-name:none;animation-name:none}
body[data-device="phone"] > section[data-transition="none"][data-direction="back-out"]{z-index:2;-webkit-animation-name:none;-moz-animation-name:none;-ms-animation-name:none;-o-animation-name:none;animation-name:none}

Now, you can use data-transition="none" for sections where you don't need any transition.

**Comment by vtellez** [comment]
@maytis your code does not seem to work for me... If I use it and change my data-transition="none", then any link between transition work..

any ideas?
