### ISSUE TITLE
Article TRIGGER.LOAD not fired when section is loaded

### ISSUE THREAD

**Issue by cadu-goncalves** [tapquo/Lungo.js#257]
If I use a layout like this:

&lt;section id="s1"&gt;
        &lt;article id="a1" class="active"&gt;&lt;/article&gt;
        &lt;article id="a2"&gt;&lt;/article&gt;
&lt;/section&gt;

When section#s1 is loaded, Lungo must also fire the load for the active article#a1.

**Comment by soyjavi** [comment]
Yap, this is da' purpouse :)

**Comment by cadu-goncalves** [comment]
That was a great answer, I don't know how do you intended to build a community around your projects with answers like that, but that's your problem not mine.

The point is when I load a Section that uses a layout based on Footer > Nav or Header > Nav, and I wan't to load data inside first article (the active one), I'am supposed to use (tha is what the documentation in your project saids) the Article#LOAD event however, it doesn't work and I need to listen the Section#LOAD event to feed the First article with content and the respective Article#LOAD events for the other articles inside the same Section. 

Does it really make sense to you? If so, no problem  I've just fixed (or call it as you wan't if you thing that your are able to solve everything at first try I realy envy you for that) it by myself,  I just belived that some other users would like to work that way as well.

Best regards.

**Comment by maytis** [comment]
@ cadu-goncalves, Could you please share the solution.

**Comment by fer-ri** [comment]
Could you share your solution?
Because i cant make this code to work

```
Lungo.dom('#section1').on('unload', function(event) {
    alert("Unloaded section 1");
});

Lungo.dom('#section2').on('load', function(event){
    alert("Loaded section 2");
});
```
