### ISSUE TITLE
Checkboxes y Radio Buttons

### ISSUE THREAD

**Issue by rickycheers** [tapquo/Lungo.js#26]
Hola estoy probando el framework (muy buen trabajo hasta ahora) y quise experimentar con los elementos de formulario y noté que los elementos "checkbox" y "radio" parecen no funcionar correctamente.

Al ver el código CSS ambos elementos tienen "opacity:0;"

¿Esto es correcto?¿Aún no están dando soporte a estos elementos o es un simple "bug"?

Este es el código de muestra que se encuentra en el Sitio:
`<p class="form">
<input type="text">````
    <input type="text" placeholder="Input text"/>
    <input type="password" placeholder="Input password"/>
    <input type="checkbox">Save credentials</input>
    <textarea placeholder="Textarea sample"></textarea>
    <label class="select">
        <select class="custom">
            <option value="1">One</option>
            <option value="2">Two</option>
            <option value="3">Three</option>
        </select>
    </label>
</p>

```
```

**Comment by soyjavi** [comment]
Do you use release 1.0.2?

**Comment by rickycheers** [comment]
Yes I do

**Comment by soyjavi** [comment]
What version of browser are you using on your phone?

**Comment by rickycheers** [comment]
I'm using iOS Simulator with iOS 5, don't know specifically which Safari Mobile version is.
I'm also using Chrome 15, Safari 5.1.2.
Haven't been able to test it on my Android Device. I'll let you know when I do it.

Kind Regards!

**Comment by hell03610** [comment]
Yes, it's also in 1.0.3

input[type="checkbox"], input[type="radio"] {
filter: alpha(opacity=0);
-moz-opacity: 0;
-webkit-opacity: 0;
opacity: 0;
}

If i revome opacity, it's shown but it's not properly aligned with its text

**Comment by campsjos** [comment]
I think it may be because you need to put `<label class="checkbox">` before the `<input type="checkbox">`, and close it after.

**Comment by rickycheers** [comment]
Ok, it worked
