### ISSUE TITLE
Scrolling List Error over Android with KitchenSink example

### ISSUE THREAD

**Issue by flachica** [tapquo/Lungo.js#274]
Discussed: https://groups.google.com/forum/#!topic/lungojs_es/vcuKuVxm2Bc
and: https://groups.google.com/forum/#!topic/lungojs/Ga_RF4Cteto

I tried to deploy the full example Lungo (KitchenSink) on my Xperia U (Android 2.3.7 WebKit/533.1) and messing with the lists I have found that gives an error that causes it to freeze the screen and not keep doing Scroll by all the elements of the list.

09-14 17:16:54.000: W / webview (19746): Miss a drag as we are waiting for WebCore's response for touch down.

I just embedded the example of the web in a webView and the welcome screen I scrolled to bottom for the buttons "Tweet Me" and "Go to Project's page"

Are you going on your mobile?

I try this http://stackoverflow.com/questions/10933207/how-to-fixmiss-a-drag-as-we-are-waiting-for-webcores-response-for-touch-down
but not work for me.

**Comment by jelmervisser** [comment]
I also see that warning a lot with scrolling on Android 2.3.3 and early devices.
