### ISSUE TITLE
data-search =

### ISSUE THREAD

**Issue by daithiw44** [tapquo/Lungo.js#29]
In an Article of class .list where data-search is set there are the following issues.

Issue 1. The LUNGO.Attributes.Data for &#39;search&#39;  will return the li and its not inside a &lt;ul&gt;

```
    search: {
     tag: 'search',
     selector: '.list',
     html: '<li class="search {{value}}"><input type="search" placeholder="Search..."><a href="#" class="button" data-icon="search"></a></li>'
 },
```

Is the intention to have this as part of the list being created or to be inside its own &lt;ul&gt;?

Issue 2. When build a article of class .list dynamically from a template with data-search the ul placeholder will never be build because of the following function

var _createListElement = function(article) {
// The data-search will already have created a child
        if (article.children().length === 0) {
            var article_id = article.attr(&#39;id&#39;);
            article.append(&#39;&lt;ul id=&quot;&#39; + article_id + &#39;_list&quot;&gt;&lt;/ul&gt;&#39;);
        }
    };

the article with the attribute data-search will already have children as when the page is being rendered the  lng.View.Template.Binding.dataAttribute(element, attribute) will create an innerHTML for LUNGO.Attributes.Data.search and so the &lt; ul&gt; will never be built and so there will be no element to attached scrolling or the template to.

Suggestion.
1. On LUNGO.Attributes.Data  search.

Be good to give both the &#39;input box&#39; and the &#39;a href&#39; an id based on the article id so that its easy to add events to the buttons. So something like:

&quot;&lt;li class=&quot;search {{value}}&quot;&gt;&lt;input type=&quot;search&quot; id=&quot;search_{{ article_id}}&quot; placeholder=&quot;Search...&quot;&gt;&lt;a href=&quot;#&quot; class=&quot;button&quot; data-icon=&quot;search&quot; id=&quot;sbtn_{{ article_id}}&quot;&gt;&lt;/a&gt;&lt;/li&gt;&quot;

and also what might be the easiest way out would be to have the following

OPTION A)
 A separate ul for the search

&quot;&lt;ul id=&quot;searchul_&quot;{{article_id}}&gt;&lt;li class=&quot;search {{value}}&quot;&gt;&lt;input type=&quot;search&quot; id=&quot;searchtext_{{ article_id}}&quot; placeholder=&quot;Search...&quot;&gt;&lt;a href=&quot;#&quot; class=&quot;button&quot; data-icon=&quot;search&quot; id=&quot;searchbtn_{{ article_id}}&quot;&gt;&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&quot;

Give the template the articleid appending to a  string for the ul, the input box and the a href search button. This will make attaching events to these elements easier.

ul has id = &#39;searchul_&#39; + articleid
input box has id = &#39;searchtext_&#39; + article_id
search button has id = &#39;searchbtn_&#39; + article

handle the replace inside 

  var dataAttribute = function(element, attribute) {
        var data = element.data(attribute.tag);
        if (data) {
                      // handle the replace for search
            if(attribute.tag === &#39;search&#39;){
                var regex;
                regex = new RegExp(BINDING_START  + &#39;article_id&#39; + BINDING_END, &quot;g&quot;);
                var html_binded = attribute.html.replace(regex, element.attr(&#39;id&#39;));
                html_binded = html_binded.replace(BINDING_START + &#39;value&#39; + BINDING_END, data);
            }
            else{
            var html_binded = attribute.html.replace(BINDING_START + &#39;value&#39; + BINDING_END, data);
            }
            element.prepend(html_binded);
        }
    };

Then make a change in  function createListElement to check if there is 1 child we&#39;ll know the id format node type etc of the 1 child and if so create the new ul and append it to the article.

OPTION B)
The other option is to create the ul from the data-search

&quot;&lt;ul id=&quot;{{article_id}}_list&quot;&gt;&lt;li class=&quot;search {{value}}&quot;&gt;&lt;input type=&quot;search&quot; id=&quot;searchtext_{{ article_id}}&quot; placeholder=&quot;Search...&quot;&gt;&lt;a href=&quot;#&quot; class=&quot;button&quot; data-icon=&quot;search&quot; id=&quot;searchbtn_{{ article_id}}&quot;&gt;&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&quot;

only problem here is when we build our li element via template we clear the contents of the ul and hence remove the search li. so there would be more work here, especially if adding and removing li elements based on the filter.

I&#39;ve implemented Option A) locally and will test shortly, I&#39;ll commit it to my fork 

https://github.com/daithiw44/Lungo.js/commit/740759b67500352fe497a70f0ad90a5c9e94d04d
if you&#39;re interested in that as a fix and see if you want it as a pull request.

Let me know what you think or if you need more information.

Daithi

**Comment by phil-hudson** [comment]
Has there been any advance on this? I'm having a similar issue...
