### ISSUE TITLE
Lungo.Notifications don't work.

### ISSUE THREAD

**Issue by MrPoofy** [tapquo/Lungo.js#291]
Hi!

Every time and every way i try to use the "Lungo.Notification" method i get a undefined error. For example, i use this notification example:

```
var afterNotification = function(){ //Do something};
Lungo.Notification.error(
    "Error",                                
    "Unsuccessful operation",     
    "cancel",                             
    7,                                       
    afterNotification                   
);
```

And when i try to use him i get this "Quo" error:

```
"Uncaught TypeError: Cannot read property 'className' of undefined"
```

**Comment by MrPoofy** [comment]
Just get them to work. To resolve this problem just call your 'quo.js' and 'lungo.js' files at the end of the 'index.html' file.

**Comment by adnbsr** [comment]
Check quojs version

**Comment by MrPoofy** [comment]
I already got it to work, you just need to add the quojs at the end of the index.html file.
