### ISSUE TITLE
Issue on android

### ISSUE THREAD

**Issue by ajitbohra** [tapquo/Lungo.js#294]
Planning to use lungo as frontend for android app managed to setup and run the example on localhost (It worked on local server wamp but error on opening example direct from filesystem). Tried to test example on android webview app but aside menu is not working !

**Comment by cureorcurse** [comment]
Android 4.1 and below got issue with aside. 4.1 and above no issue with
aside. based on My experienced

**Comment by ajitbohra** [comment]
- I am using it with Android 4.1.2 amd still its not working
- Also  Lungo cannot be used from file system
- We need to place it on web server to work 
- I dont understand why we need to place it on webserver to work as it will be used as frontend for app in webview or phonegap not on server

**Comment by cureorcurse** [comment]
I'm using phonegap with Lungo 2.2 works like charms. Not sure y yours not
working.

**Comment by ajitbohra** [comment]
- I am currently using it with plain android webview and its not working
- Will try with phonegap

**Comment by soyjavi** [comment]
We've apps with Android 4.1, 4.2, 4.3 … and works :/
-- 
Javi Jiménez Villar
Founder at @tapquo

On 18 de noviembre de 2013 at 08:45:41, cureorcurse (notifications@github.com) wrote:

I'm using phonegap with Lungo 2.2 works like charms. Not sure y yours not
working.

**Comment by ajitbohra** [comment]
@cureorcurse @soyjavi Can you quickly brief me with your setup app what steps you took to get the lugngo setup.

**Comment by cureorcurse** [comment]
1. Normal Phonegap setup.
2. For Lungo, I replicate the demo from http://lungo.tapquo.com/demo/

Nothing fancy.

**Comment by ajitbohra** [comment]
@cureorcurse how do you replicate demo or get complete files for lungo. Initially i downloaded zip file from github and extracted the files but many of the files were missing from it. quojs and some file have to download and separately copy them in the folder.

**Comment by cureorcurse** [comment]
Bro, the easiest way to get a complete lungojs demo is by viewing the
sourcecode from the demo site. Its painful but worthit.

Simply copy those source code to respective file.
This is not an elegant way to replicate. But I did it within less than15
minutes.

All works properly as in the demo. If not working at first time. Try copy
to yr www folder on phonegap n run.

I'm not sure this method can work for everybody, but mine is working
properly. Except some features need tweak at css level.

**Comment by ajitbohra** [comment]
Ok will try as suggested!

**Comment by ajitbohra** [comment]
Managed to get it run with Phonegap:

Few things would like to share
- When we download the zip package from github provided example file do not work
- lungo folder in packages is empty (Core loungo file are required) so needed to manually browse git repo and grab the files
- Component folder is empty (quojs is required  in order to get things working) needed to manually browse git repo and grab the files
- Once everything is in place and if we are on file system (local folder or drive) aside menu will not work and console gives this error "XMLHttpRequest cannot load file:///D:/PhoneGap/www/static/asides/features.html. Cross origin requests are only supported for HTTP."
- On Local wamp server everything works fine
- Initially tried to create simple android webview app but like local file system aside menu doesn't work
- So lungo with all file in place with webserver or Phonegap are needed to make things go smooth.
- Hope this will help someone
- Wish to have better initial set-up documentation & faq, ready to help if needed
- Few other issues currently trying to figure out & browse other issue to check

Thanks for this amazing framework i am loving it hope to soon develop some awesome apps with this amazing framework :)
