### ISSUE TITLE
Pantalla negra en Blackberry

### ISSUE THREAD

**Issue by jsmiguel** [tapquo/Lungo.js#302]
Tengo el problema para blackberry, en android me funciona perfecto, pero en blackberry se muestra la pantalla en negro, solo logra mostrarse una parte de la barra de título.

¿Hay alguna propiedad específica que debo agregar para que funcione correctamente en blackberry?

Probado en Blackberry 9220

**Comment by soyjavi** [comment]
Lo siento, pero con esa información no puedo ayudarte. De todas formas decirte que LungoJS está testeado en entornos Blackberry OS6/7 y 10.
