### ISSUE TITLE
ajax cross domain issue - Service

### ISSUE THREAD

**Issue by davidleiwang** [tapquo/Lungo.js#307]
Hi there, 

I am following example try to GET data with ajax call.

when i am using the following URL, I can get data as expected
var url = "http://127.0.0.1:8888/lungo/x.php";

when i am using the following URL, 
var url = "http://myexternaldomain.com/x.php";

I got the following message 
No 'Access-Control-Allow-Origin' header is present on the requested resource

seems to be cross domain issue, yet i already set crossdomain to true, see below

```
    Lungo.Service.Settings.async = false;
    Lungo.Service.Settings.error = function(type, xhr){
        Lungo.Notification.html('<h1>connection error</h1>', "Close");
    };
    Lungo.Service.Settings.headers["Content-Type"] = "application/json";
    Lungo.Service.Settings.crossDomain = true;
    Lungo.Service.Settings.timeout = 10;
```

Can any1 please help?

**Comment by soyjavi** [comment]
I think it's your server (myexternaldomain.com) policy.

**Comment by davidleiwang** [comment]
thanks, it worked
