### ISSUE TITLE
If a text is long enough you cannot see the whole text in a <li>

### ISSUE THREAD

**Issue by BraulioVM** [tapquo/Lungo.js#31]
I have been doing some apps with your framework and I have one thing to say to you: awesome!

I have found a problem which I don't know if I could solve on my own, I think I couldn't do it well. Well, the problem is that if you have a list item element with a long text, you would not be able to see the whole text.

For example:
http://imageshack.us/photo/my-images/855/screenshot5ci.png/

This example is not that bad, but, when I test the app in an iphone, as the screen is smaller, there's always a lot of text out of the screen.

I don't know why this problem happens and don't know how it could be solved, but I'm trying it.

Thanks

**Comment by soyjavi** [comment]
The <strong> element in a <li> has a display:block property, for this reason it appears on one line... You must use the CSS properties to indicate that the text continues: 

white-space:nowrap;
text-overflow:ellipsis;

**Comment by magojhonblack** [comment]
si quiero que ese mismo texto ocupe dos lineas y hay si termine con puntos suspensivos como lo haría.

**Comment by soyjavi** [comment]
You must know CSS :)
