### ISSUE TITLE
data-view-section funciona 1 sola vez. Despues deja de funcionar.

### ISSUE THREAD

**Issue by marcelo-kazalukian** [tapquo/Lungo.js#340]
Hola. Dentro de mi body tengo lo siguiente.
3 secciones, cada una con un boton que lleva a la siguiente. 
Al presionar el boton de la Seccion_1 se abre la seccion_2. 
Pero al presionar el boton de la Seccion_2 no se abre la Seccion_3, por que?

Lungojs: v2.2.1
quojs: v2.3.6

```
    <section id="Seccion_1">
    <header data-title="Seccion 1"></header>
    <article class="active">
        <a href="#" data-label="Ir a seccion 2" class="anchor button" data-view-section="Seccion_2"></a>
    </article>
</section>

<section id="Seccion_2">
    <header data-title="Seccion 2"></header>
    <article class="active">
        <a href="#" data-label="Ir a seccion 3" class="anchor button" data-view-section="Seccion_3"></a>
    </article>
</section>

<section id="Seccion_3">
    <header data-title="Seccion 3"></header>
    <article class="active">
    </article>
</section>  
```

**Comment by soyjavi** [comment]
Hi Marcelo,

I've just check your code.. and works fine :). One trick, use id in lowercase... I think you have a typo error.

best,

**Comment by marcelo-kazalukian** [comment]
Javi, me recomendas poner los id solo con minusculas? cuando son varias palabras que recomendas para que sea facil la lectura? puede ser el guion abajo? por ejemplo: pantalla_principal

Gracias.

**Comment by soyjavi** [comment]
It's a convention, lowercase for ALL "id" & "class" attributes.
