### ISSUE TITLE
Scroll Android

### ISSUE THREAD

**Issue by hugohabel** [tapquo/Lungo.js#36]
I almost finish my first mobile site with Lungo. It is awesome.

I am having a problem with the scroll in Android (2.2), it is only on the native browser, on Firefox it works. It is working perfect in iPhone 4S, iOS 5.

This is my code:

<scroll id="result_main_scroll" class="scroll"></scroll>

I add elements to this scroll using Javascript.

**Comment by soyjavi** [comment]
I don't see your code... can you tell me the site :)

**Comment by campsjos** [comment]
Are you using the Lungo template system?
http://www.lungojs.com/api/#doc-view-template

Also, you can add elements to an scrollable container with iScroll
http://www.lungojs.com/api/#doc-scroll-update

Good luck!
