### ISSUE TITLE
Scroll para datos externos ajax 

### ISSUE THREAD

**Issue by magojhonblack** [tapquo/Lungo.js#37]
tengo un pregunta tengo una sección donde los datos son llamados atreves de ajax, pero cuando los datos son demasiados largos este  hace scroll, si no que simplemente corta hasta donde alcance la pantalla,  cual es el procedimiento para darle scroll a un articulo que inicia vació pero después de una llamada se le insertan datos?

**Comment by soyjavi** [comment]
You must:

<scroll id="type-a-scroll-id">
 <div class="container-scroll" style="height: ?px">
     
</div>
</scroll>

**Comment by magojhonblack** [comment]
<! scroll id="type-a-scroll-id">
   <! div class="container-scroll" style="height: ?px">
    
  <! /div>-->
  <!/scroll>

Muchisimas gracias por el codigo si funciono.

**Comment by magojhonblack** [comment]
tengo otro problema, si le pongo un numero muy bajo de px para el scroll este simplemente se devuelve pero si lo pongo muy grande este queda mucha pagina en blanco y si lo pongo en auto este simplemente no hace nada, alguna sugerencia.

**Comment by soyjavi** [comment]
You must calculate the correct height :)
