### ISSUE TITLE
asynchronically loaded lists

### ISSUE THREAD

**Issue by campsjos** [tapquo/Lungo.js#38]
I load some data with `lng.Service.get` from a JSON file and then generate an HTML list with common javascript.
There's my code:

``` javascript
lng.Service.get(url, '', function(response) {
            for (i in response.apartment){
                name=response.apartment[i]['@attributes']['name'];
                liStr += '<li data-icon="home">\n';
                liStr += '  \t<strong>'+name+'</strong>\n';
                liStr += '</li>';
            }
            liStr += '</ul>'
            document.getElementById('apart_list').innerHTML=liStr;
        });
```

The HTML code is generated fine, but it doesn't show the icons and doesn't scroll, I think it's because the "data-icons" are parsed only once when the app is loaded.
There is any solution or i have to add the `<span class="icon home"></span>` manually? Thanks!

**Comment by campsjos** [comment]
I'm noob with js frameworks, probably i'm doing something bad...

**Comment by dblugeon** [comment]
Hi @campsjos ,
You should use the lungo's template system.

I have used this to populate an aside element's content and main content with webstorage/json data.

doc : http://www.lungojs.com/api/#doc-template-create
exemple of template here : https://github.com/TapQuo/Lungo.js/tree/master/examples/todo.js

**Comment by campsjos** [comment]
Thanks @dblugeon i'll take a look on it right now :)

**Comment by campsjos** [comment]
Ok, now I have a much more clean code, and the scroll works fine, but i still have to add `<span class="icon home"></span>` manually.
As I see in the examples, they put that `span` manually too, so it should be the only way to do it.
Thank you again @dblugeon

**Comment by ohrstrom** [comment]
Hi there
how should this be done with the current version of lungojs? what templatieng system could be used that can be dynamically parsed? or is there a way to re-run the parser after dom updates?

thanks a lot
