### ISSUE TITLE
Aside and search

### ISSUE THREAD

**Issue by JordiPay** [tapquo/Lungo.js#39]
Cuando el Aside esta desplegado la lupa del search no se ve. Para telefonos no es problematico ya que se puede contraer el aside, pero para tables no puedes hacer click en la lupa.

When Aside is shown the icon for search is not showed. For smartphones is not a problem becouse aside can he hidden, however for tablets you cannot click on the search icon.

(Tested on Chrome 16.0.912.63 m by making the screen small-big)

**Comment by soyjavi** [comment]
Think that LungoJS is for mobile environments (no Desktop environment) ... Have you tested on real mobile environments android / IOS?
