### ISSUE TITLE
Calendar icon doesn't work

### ISSUE THREAD

**Issue by javiercr** [tapquo/Lungo.js#4]
The calendar class doesn't shows the calendar icon. I've tried with other icons and they work fine, but the calendar one doesn't show up.

**Comment by soyjavi** [comment]
Uhmmm .. I will check and tell you something:)

Thanks man:)

**Comment by jsmanrique** [comment]
I've found a solution:
On lungo-1.0.0.min.css, it seems there is a bug in the icon definition:
icon.index:before{content:'i';}

it should be:
icon.index:before{content:'l';}

**Comment by soyjavi** [comment]
FIXED on Commit https://github.com/TapQuo/Lungo.js/commit/9ad1c6833acdd4341fee3449c8424d8e369adfba

**Comment by javiercr** [comment]
Awesome, thanks!

Sorry I didn't have time to take a look into it. Congrats for the framework!
