### ISSUE TITLE
lng.Dom.Event.live doesn't work on iPad

### ISSUE THREAD

**Issue by campsjos** [tapquo/Lungo.js#41]
Hi! it seems lng.Dom.Event.live() does not work on iPad, i don't tested it on iPhone...
Here the code I used to test this issue: 

index.html (all the content inside `<body>` tags)
`<section id="section1">
        <header data-title="Section 1"></header>
        <article class="list">
            <ul>
                <li class="link_li" data-icon="home">
                    <strong>Content</strong>
                    <small>Extra info</small>
                </li>
                <li class="link_li_live" data-icon="home">
                    <strong>LIVE</strong>
                    <small>Extra info</small>
                </li>
                <li class="link_li" data-icon="home">
                    <strong>Content</strong>
                    <small>Extra info</small>
                </li>
                <li class="link_li_live" data-icon="home">
                    <strong>LIVE</strong>
                    <small>Extra info</small>
                </li>
            </ul>
        </article>
        <footer></footer>
    </section>
    <section id="section2">
        <header data-title="Section 2"></header>
        <article>
            <br/>
            <h1>This is section 2</h1>
            <a href="#section1" data-target="section" class="button red big">Link to list</a>
        </article>
        <footer></footer>
    </section>`

events.js
`lng.Dom.Event.live('.link_li_live', 'TAP', function(event) {
        lng.Router.section('section2')
        });
    lng.Dom.Event.bind('.link_li', 'TAP', function(event) {
        lng.Router.section('section2')
        });`

Tested on Chrome 16.0.912.63 m, Android 2.2 and iPad2 Safari, It only fails on iPad

**Comment by soyjavi** [comment]
In iPad first gen??

**Comment by campsjos** [comment]
no, in iPad2...

**Comment by soyjavi** [comment]
Don't worry, right now I'm developing QuoJS (http://quojs.tapquo.com) which will have a better touch support.

**Comment by campsjos** [comment]
?? then, Lungo will be deprecated? QuoJs is an improvement of Lungo or it is an independent project? I ask this because I need to know if the application i'm developing with Lungo will ever have compatibility with iPad or I have to wait for QuoJS...

**Comment by soyjavi** [comment]
No no!!! QuoJS it's a CORE Component in LungoJS project :) Zepto is currently used as the DOMhandler and event listeners, this library is not as powerful as we'd like so that's why I'm developing QuoJS.

Your rest assured, your development will not be affected by the release 1.1 of LungoJS

**Comment by campsjos** [comment]
:D
