### ISSUE TITLE
Problema en aside lungo 1.0.4

### ISSUE THREAD

**Issue by dpbataller** [tapquo/Lungo.js#44]
Hola Javi, estoy experimentando problemas al usar la feature aside de lungo.
Cuando pulso el botón para que se expanda el aside izquierdo y intento hacer scrolldow o scollup, se cierra el aside de forma brusca sin dejar hacer el scroll, cómo ya te he dicho.
Lo estoy probando en el iphone físico.
Probándolo en Safari con agente de usuario iPad, funciona bien.
Por cierto, con el Kitchen Sink también me pasa... NO puedo hacer scroll en el aside... se cierra.

**Comment by soyjavi** [comment]
Thanks!! I'll check

**Comment by soyjavi** [comment]
Buf Fixed with this commit:
https://github.com/TapQuo/Lungo.js/commit/e6aed53447b72ab159c20424028fa2377ecefa31
