### ISSUE TITLE
Little mistakes on API documentation

### ISSUE THREAD

**Issue by campsjos** [tapquo/Lungo.js#45]
[Event.undelegate()](http://www.lungojs.com/api/#doc-event-undelegate) and [Event.die()](http://www.lungojs.com/api/#doc-event-die) have the same description: "Add an event listener."

In the example code of [List.create](http://www.lungojs.com/api/#doc-template-list) you show us `lng.View.Template.create(config);` and it must be `lng.View.Template.List.create(config);`

That's all, good work!!

**Comment by soyjavi** [comment]
Bugfixes :)

**Comment by campsjos** [comment]
AKA little mistakes :)
