### ISSUE TITLE
Error al mostrar datos String Solo números.

### ISSUE THREAD

**Issue by Jacen** [tapquo/Lungo.js#48]
Buenos dias Javi,
No he tenido tiempo de revisarlo, pero el problema es que tengo una vista creada en la que muestro un codigo de un Empleado, que solo tiene números, por ejemplo 0002, Lungo automáticamente lo parsea y te muestra un 2.
Entiendo que no debería hacerlo.

**Comment by soyjavi** [comment]
Lo siento pero ese no lo esta haciendo LungoJS a menos que estes ordenando...

**Comment by Jacen** [comment]
Creo que he encontrado el fallo.
Lungo.js / src / data / Lungo.Data.Sql.js
linea 194:                 values += (isNaN(value)) ? '"' + value + '"' : value;
imaginate que en value viene un string "0001" al meter el valor sin comillas simples en la sql los hace entero.
No he probado como hacerlo correctamente,  pero creo que con esto quizas te valga para ver el fallo.

**Comment by soyjavi** [comment]
Crack!!! Le echo un vistazo ... Si hubieses empezado por ahi ;)

Javi Jiménez Villar
CEO & Creative Lead
Tapquo Inc.

On 19/01/2012, at 18:17, Jacen
reply@reply.github.com
wrote:

**Comment by Jacen** [comment]
Para otra vez, que es lo que tengo que hacer en github para mandaros
una modificacin solucionando el fallo??

El 19 de enero de 2012 18:41, Javier Jimnez <
reply@reply.github.com
