### ISSUE TITLE
No changes by setting value for input-fields via script

### ISSUE THREAD

**Issue by christianarth** [tapquo/Lungo.js#49]
Hi,

No changes in view when:

$('#my_input_field').attr('value', '');

or

$('#my_input_field').attr('value', 'test');

or

$('#my_input_field').removeAttr('value');

(the code was updated as expected so zepto does his job)

My Device: HTC HD 2 with Android

regards
chris

**Comment by soyjavi** [comment]
Why not use the val() method?

```
var value = $(selector).val();

$(selector).val('test');
```

**Comment by christianarth** [comment]
.val(''); works fine!

Thanks!
