### ISSUE TITLE
Injecting new Sections to DOM

### ISSUE THREAD

**Issue by PhilippSchreiber** [tapquo/Lungo.js#50]
Hello,

I have the following case:

I have to inject new sections to the DOM. So I do:

``` javascript
$('body').append('my section html');
lng.Boot();
lng.Router.section('my-section-id');
```

If there is no active section (at startup) everything is working good. But if there are sections and one of them is active the existing section is still visible. I have an ugly workaround for it but the transition is not very nice when doing this:

``` javascript
$('body').append('my section html');
lng.Boot();
lng.Router.section('my-EXISTING-section-id');
lng.Router.section('my-NEW-section-id');
```

Probably it would be good to add a function that extends only new elements and not the whole DOM. It is strange to call lng.Boot() when the app is still running...

Do you have an idea?

Cheers
Philipp

**Comment by soyjavi** [comment]
I will study this problem more carefully and answer you ok?

**Comment by PhilippSchreiber** [comment]
Yeah sure. For now it is OK with my hack.

**Comment by PhilippSchreiber** [comment]
I've found a better workaround for that:

``` javascript
$('body').append('my section html');
lng.Boot();
lng.Dom.query('#my-EXISTING-section-id').removeClass('show').addClass('hide');
lng.Router.section('my-NEW-section-id');
```

**Comment by soyjavi** [comment]
In future versions there will be a special method:

``` javascript
lng.Router.section('my-NEW-section-id', 'URL_WHERE_IS_NEW_SECTION_MARKUP');
```

**Comment by PhilippSchreiber** [comment]
Hm but I don't load the content via AJAX. I simply have to build sections on demand from local data. So a solution like this would be much better:

``` javascript
lng.Extend('my-NEW-section-id');
```

**Comment by soyjavi** [comment]
But your solution is not semantic, 

``` javascript
lng.view.section.create('my-NEW-section-id');
```

**Comment by PhilippSchreiber** [comment]
All right, that's good for me. Will you implement it in 1.1?

**Comment by soyjavi** [comment]
Noup (maybe in 1.2) ... the branch 1.1 it's closed :)

**Comment by soyjavi** [comment]
Hi!

In version 1.2 there will be a function to load asynchronously sections (either on your local server as a remote server):

https://github.com/TapQuo/Lungo.js/commit/3e7f3adaad983a762b41052fa07af35bee6839b3
