### ISSUE TITLE
Branch 1.1 Sec Nav button don't work on Android 2.3.3 (Kitchen Sink)

### ISSUE THREAD

**Issue by DamnWidget** [tapquo/Lungo.js#51]
<b>Commit</b>: 321125513daeab74c2eee7b94e97f82b2038fe80
<b>Demo</b>: Kitchen Sink
<b>Problem</b>: Secondary Navigation button don't work at all
<b>Reproducible</b>: Always

**Comment by soyjavi** [comment]
I know this problem, in fact the navigation works but can not be mixed with a data-title. Android has a big problem with transitions and z-index (restart z-index when running a transition).

Sure I'll find a solution :)
