### ISSUE TITLE
LungoJS 1.1 not working with Sugars.Growl

### ISSUE THREAD

**Issue by mabril** [tapquo/Lungo.js#55]
When including Growl it's freezing the page.

**Comment by soyjavi** [comment]
Tomorrow is not effective release 1.1:)

**Comment by mabril** [comment]
¿Que quieres decir con eso Javi?

What do you mean with that?

**Comment by soyjavi** [comment]
Very simple, you should not use the release 1.1 until tomorrow because the sugars are not connected to the release (until tomorrow).

The rush to kill :)
