### ISSUE TITLE
No way to render a template without overwriting container

### ISSUE THREAD

**Issue by awilliams** [tapquo/Lungo.js#59]
Templates (<code>LUNGO.View.Template.Binding</code>) only have <code>create</code> method, which overwrites all content in the given container with the rendered template.

I propose a second method <code>append</code> which will append rendered content to a given container.

https://github.com/TapQuo/Lungo.js/pull/60

**Comment by soyjavi** [comment]
I'd like to accept your pull request, but the variables and methods should be more semantic (dom_fnc, $$)....
