### ISSUE TITLE
Swipe events doesn't work on event listeners

### ISSUE THREAD

**Issue by wozznik** [tapquo/Lungo.js#66]
If I added on my event.js a listener like:

``` javascript
lng.dom('article#id').on('swipeDown', function(){
   //Some code
});
```

The listener is never called, but the event is captured from QuoJS (it writes "Event swipeDown captured."  message on console). 

If I change the event type from 'swipeDown' to 'tap', the event listener is called correctly.

UPDATE:

In LungoJS 1.1.2 (QuoJS 1.0) swipe events only works in mobile environments!

**Comment by soyjavi** [comment]
Are you testing on desktop? 

If so, it is normal to not trigger the event ..only works in mobile environments:). The next release of QuoJS will be trigger touch events in desktop environments (though not their purpose).
