### ISSUE TITLE
Uncaught TypeError: Cannot call method 'trigger' of undefined

### ISSUE THREAD

**Issue by temperatio** [tapquo/Lungo.js#67]
Hi, i'm just downloaded and unzipped 1.1.2 version.

I've uncomment app info at app.js and load index.html with Chrome (or iPhone Simulator) and doing a longTap i've this error:

Using packet versión:

```
lungo-1.1.2.packed.js:51 Uncaught TypeError: Cannot call method 'trigger' of undefined
```

Using development version:

```
QuoJS.js:1102 Uncaught TypeError: Cannot call method 'trigger' of undefined
```

**Comment by soyjavi** [comment]
LongTap it's a special event for only mobile environment... no compatible with desktop environments :)

**Comment by temperatio** [comment]
ok, so, iphone Simulator is a desktop environment?

**Comment by soyjavi** [comment]
You're right, I've corrected in QuoJS Library (http://quojs.tapquo.com)

https://github.com/soyjavi/QuoJS/commit/f91318f8d638dcd4d3280c240f97ac0b7ea5a507
