### ISSUE TITLE
issues around navigation

### ISSUE THREAD

**Issue by dcsan** [tapquo/Lungo.js#68]
Trying to use the JS api to navigate from the console, some problems getting going:
- black screen

the router can find the sections i want, and the first call often works ok.
but then subsequent navigating just gives a totally black screen.
i cant really see a pattern. same section is OK sometimes, but often not.
this usually happens on 2nd/3rd api call, so its not a buried issue.

```
LUNGO.Router.History.current()
"#home"
LUNGO.Router.section("barracks")
undefined
LUNGO.Router.section("home")
undefined
```
- targeting articles isn't working?
  using as per:

`LUNGO.Router.article("barracks", "detail");`

where i know these two exist, i get:

`Lungo.Router ERROR: The target barracks articledetail does not exists.`

Are there some other methods to navigate the DOM and see what lungo does know about?

thanks!

**Comment by dcsan** [comment]
1) the issue regarding Lungo not finding articles was down to the # mark being required.
I noticed in your code:
`var section_id = (section_id.indexOf('#')) ? '#' + section_id : section_id;`
so then:
`LUNGO.Router.article("#barracks", "#detail");`
works. your checking for leading # seems inconsistent then.

2) navigation->goes to black screen issue is still not resolved.
i'll break out to a separate ticket if i can find any more pattern to it and close this one.

**Comment by soyjavi** [comment]
In the future version 1.2 I created a new object router, much more effective and simple to implement.

**Comment by amuino** [comment]
@dcsan problems with blank screen might be related to #71

**Comment by dylanbromby** [comment]
Router.article() is not working properly in 1.2. I'm not sure why this was closed.

**Comment by soyjavi** [comment]
Hello friend, honestly I don't know what your problem ... no one else has reported a similar error.

Can you show us your code?

http://www.lungojs.com/api/#doc-router-article

**Comment by dylanbromby** [comment]
I posted it on Github. The problem is, when using lng.View.Article.show or lng.Router.article, when you have two sections in the same block of code, the hide class is not removed from the section you want to navigate to and the hide class is not applied to the section you're navigating out of.

If you look at the code on Github you'll see what I mean. Also - look at http://roaringsky.com/lungo. If you use Chrome and use the Elements panel in the developer tools - watch the classes on the sections when you click the 3rd footer link.

We're working with a large startup and we really want to use Lungo for the framework so any help is appreciated. We can even pay you for your help.

Dylan

**Comment by dylanbromby** [comment]
Did you have chance to look at my reply to your email? I've attached a HTML file to this email which I hope better illustrates the issue.

Basically, we have two sections: section_one and section_two. 

"section_one" has article-1 and article-2. "section-two" has article-3.

First - it would be nice if we could have just one footer that could show for all sections but navigate between them. For now however, we have duplicated the footer in each of these sections. If you look at lines 74-90, we're trying to use the Router class to programmatically load the proper section/article but that does not work. Your documentation is somewhat limited and the only similar issue we found on the GitHub tracker was to prepend the article and section IDs with "#". That doesn't work either. 

If you can modify this code to show how you can navigate between two sections to specific articles using the Router class, that would be great.

Thanks for your help,

Dylan

**Comment by soyjavi** [comment]
Throughout this week I'll take a look to your issue
