### ISSUE TITLE
Blank screen when navigating to an already visited section

### ISSUE THREAD

**Issue by amuino** [tapquo/Lungo.js#71]
When linking to an already seen section (like ending a process and going back to the "main screen") only a black screen is displayed

**Comment by k33g** [comment]
same problem, even with 1.2 version of Lungo

**Comment by soyjavi** [comment]
You must write:

lng.Router.back();

**Comment by k33g** [comment]
it's not really a "back"
i've a main screen, and go to screen2 with : `<a href="#screen2 " data-target="section" data-icon="plus"><abbr>screen2</abbr></a>`

on screen2 i go to screen3 with : `<a href="#screen3 " data-target="section" data-icon="plus"><abbr>screen3</abbr></a>`

on screen3, i want to go directly to main screen with : (instead back + back) `<a href="#main " data-target="section" data-icon="plus"><abbr>main</abbr></a>`

sorry for my bad english

**Comment by soyjavi** [comment]
Ok:

lng.Router.back();
lng.Router.back();

Bye :)

2012/3/23 Philippe CHARRIERE <
reply@reply.github.com

**Comment by k33g** [comment]
LOL, ok
thks
