### ISSUE TITLE
version 1.1.2 works only in the packed file

### ISSUE THREAD

**Issue by regrunge** [tapquo/Lungo.js#75]
Hi, I've been using your framework for a while, I love it, but I think there are some incongruous variations between the files you uploaded. I don't think you should call "stable" a release and having only the packed version working (for a non-defined Quo object following my debug in all the other files, min included) and with a couple of bugs here and there, like at line 73 of the packed version where you find: 
a.dom(c).addClass(d.SHOW);
I believe it should be:
a.dom(c).addClass(d.SHOW);a.dom(c).removeClass(d.HIDE);
Doing that you can come back to a slide you saw before.
Now I got a problem I can't fix, using "scrollable" as a class in a article my header become scrollable (???) and 134px high.
If there are some debugs in progress can I ask you which version you can call stable and I could use in production?
Hope the hint for the line 73 I posted above can help.

Thanks for the GREAT job anyhow, I love your framework but I believe should be more clear the connection with Quojs, I used its API to learn how to use Lungo, but well, all can be improved and you are 99% done for what I saw!

BTW: what's sugar? That's not clear to me
Goodbye!

**Comment by soyjavi** [comment]
Have you included the libraries and iscroll & quojs?

**Comment by tunelko** [comment]
Hi ! 

You have to include both iscroll & quojs to work with the unminified or unpacked lungojs version, like Javier said.  
Sugar is a kind of 'complement'  that you can combine to create powefull webapps. More information at the repository: 

https://github.com/TapQuo/Lungo.Sugars
