### ISSUE TITLE
Bug en scroll

### ISSUE THREAD

**Issue by cristianferrarig** [tapquo/Lungo.js#78]
Cuando hago scroll vertical en cualquier dirección con origen en un elemento de formulario (input, textarea, select), se hace scroll también en el webview y hace que se recorte la pagina.

Esto pasa ya sea en el propio safari como también en el modo web app.

Saludos ;-)

**Comment by soyjavi** [comment]
En la version 2.0 no existirá ese bug, ten en cuenta que para el control de scroll se utiliza la librería iScroll... y es un error derivado de esa libreria.

Estoy trabajando en un scroll nativo para la versión 2.0.

Paciencia :)
