### ISSUE TITLE
Problem with scroll by rotating the mobile

### ISSUE THREAD

**Issue by rafaelreyes** [tapquo/Lungo.js#79]
Hello

I have a problem with scrolling by rotating the phone, I have understood that the scroll is added to the list only if needed. I have a list to be horizontal, for space is added the scroll, the change to vertical scrolling is still present, when I start the list vertically, does not need the scroll, but to rotate it to landscape, there have scroll if necessary but, as initially put it, is descuedra the screen and scroll the entire screen and not on the list.

No way to fix this manually, or by code indicate if scroll applies even when not needed?
The LungoJS version I use is 1.2
Regards

**Comment by soyjavi** [comment]
Is on Android Device?

**Comment by rafaelreyes** [comment]
Android and IOS, workarround implemented in the method "resize", comparing that item is visible and refresh the list 

<pre>
lng.dom(window).on('resize', function(event) {
        if (currentArticle==='article-1'){
           lng.View.Scroll.refresh('article-1');
        }else if (currentArticle==='details'){
             //other method
        }
 });

</pre>

**Comment by soyjavi** [comment]
In LungoJS2 we've a native scroll :)

bye bye iScroll
