### ISSUE TITLE
index icon shows info icon

### ISSUE THREAD

**Issue by jsmanrique** [tapquo/Lungo.js#8]
it seems strange, but reading lung-1.0.0.min.css I see this:
icon.index:before{content:'i';}

And it is the same than icon.info.before, so, it shows "info" icon:
icon.info:before{content:'i';}

But reading the TTF file, it seems that it should be an "index" icon. 

So, it seems, it should something like:
icon.index:before{content:'l';}

This also solves the "calendar" icon issue

**Comment by soyjavi** [comment]
You're right... in v.1.0.1 will be fixed :)

Thanks man!
