### ISSUE TITLE
Router.article() isn't working

### ISSUE THREAD

**Issue by dylanbromby** [tapquo/Lungo.js#83]
Router.article() isn't working in 1.2. Verified the section and article exist in the DOM at the time we're trying to fire it. Events before and after Router.article() are firing. When we try Router.section() we get a black screen but Router.article() does nothing at all.

**Comment by dylanbromby** [comment]
Here's some sample code. Clicking the third icon in the footer fires the script at the bottom (uncomment the console.log and you'll see the code block executes) but the Router fails. Shouldn't it load the article "test" in the section "copyright"?

```
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>LungoJS 1.2</title>
    <meta name="description" content="">
    <meta name="author" content="Javier Jiménez Villar (@soyjavi)">
    <!-- Mobile viewport optimization http://goo.gl/b9SaQ -->
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta http-equiv="cleartype" content="on">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <!-- For iPhone 4 with high-resolution Retina display: -->
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/images/icon@2x.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/images/icon-72.png">
    <link rel="apple-touch-icon-precomposed" href="assets/images/icon.png">
    <link rel="apple-touch-startup-image" href="assets/images/default.png">
    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="lungo/lungo-1.2.css">
    <link rel="stylesheet" href="lungo/lungo.theme.default.css">
</head>

<body class="app">
    <!--
        First, you have to do is create a LungoJS Application instance in the file app.js.
        ...and use a Webkit browser as Chrome or Safari.
    -->
    <section id="hello_world">

        <header data-title="Hello world!">

            <a href="#aside-example" data-target="aside" data-icon="files" class="button onleft">Aside</a>
            <a href="#copyright" data-target="section" data-icon="files" class="button onright">Copyright</a>

        </header>

        <footer class="toolbar with-labels">
            <nav>
                <a href="#article-1" class="current" data-target="article" data-icon="user" data-label="User"></a>
                <a href="#article-2" data-target="article" data-icon="group" data-label="Group"></a>
                <a id="tester" href="#article-3" data-target="article" data-icon="folder" data-label="Folder"></a>
            </nav>
        </footer>

        <article id="article-1">article 1</article>
        <article id="article-2">article 2</article>
        <article id="article-3">article 3</article>

    </section>

    <section id="copyright">
        <header data-back="home" data-title="Copyright"></header>
        <article id="test">test</article>
    </section>

    <aside id="aside-example"></aside>



    <!-- LungoJS (Production mode) -->
    <script src="lungo/lungo-1.2.js"></script>
    <!-- LungoJS - Sandbox App -->
    <script src="app/app.js"></script>
    <script src="app/data.js"></script>
    <script src="app/events.js"></script>
    <script src="app/services.js"></script>
    <script src="app/view.js"></script>

    <script>

        $$('#tester').tap(function(){
            //console.log('test');
            LUNGO.Router.article("copyright","test");
        });  

    </script>

</body>
</html>
```

**Comment by xoan** [comment]
I think that is the normal behaviour if you've already assign a valid `href` and `data-target` attributes to the `a` element you are trying to bind the event.

But the current problem is that `lng.History.Router.article(section, article)`does not work at all in any scenario unless param `section` and `lng.Router.History.current()` had the same value, it is: you are in the same section you are trying to go :)

But related to this, is that if you try `lng.Router.section(section)`and the current section is equal to `section`, you get an awesome blank page.

Both of this bugs are fixed in the current development branch: https://github.com/TapQuo/Lungo.js/blob/2.0/src/router/Lungo.Router.js

**Comment by dylanbromby** [comment]
Hi Xoan -

This is what one of our developers found using the dev branch:

Ok, so, the Router method works on the surface but the it doesn't actually switch the sections. We get an error after switching sections because Lungo thinks we're in the old section.

--Dylan

**Comment by jhg** [comment]
use first a secction routing and use article routing.

**Comment by dylanbromby** [comment]
Do you have a working code example?

**Comment by jhg** [comment]
Yes:

lng.Router.section('sectionexample');
lng.Router.article('sectionexample', 'articleexample');

This is a bug of LungoJS, but with this two lines work good.

**Comment by dylanbromby** [comment]
That doesn't work either.

If you have the following in a single HTML file:

<section id="section1">

```
<article id="article1"></article>
```

</section>

<section id="section2">

```
<article id="article2"></article>

<footer>

    ... some navigation ...

</footer>
```

</section>

Then you want to tap on a footer link in section2 to take you to section1/article1 the following does not work:

lng.Router.section('section1');
lng.Router.article('section1','article1');

Lungo throws an error saying "The target does not exists >>>section#section1; The target does not exists >>> section#section1 article#article1

--Dylan

**Comment by jhg** [comment]
what version of LungoJS you use? I work with 1.2

LungoJS have many errors and little documentation. The author of LungoJS not think this is a problem because say that have 16K developments use LungoJS.

**Comment by dylanbromby** [comment]
Yes, 1.2. It's very buggy.

**Comment by jhg** [comment]
I use 1.2 and work, I donk know this bug, in twitter can speak with the author of Lungo, but I don't believer.
Lungo have more posibilitys but is bad documentation, more errors bugs, etc, and author as have 16k users don't help with documentation, I have one project with Lungo, no more in the future because bad documentation. And if bugs don't fixed,is bad for Lungo.

**Comment by dylanbromby** [comment]
They're working on 2.0 now. If they fix the bugs I think the framework has promise. We've been hacking their core to make things work and so far it's going OK but we're not done yet. So ... we will see.

Dylan

**Comment by jhg** [comment]
I undertand, but I think that documentation is very important, I in my house can use more time in learn myself about Lungo and not ever, if I can't use more time, I don't use Lungo and use other.

**Comment by soyjavi** [comment]
jhg >> Nobody forces you to use LungojS. It's a personal project and you can not demand anything. In Tapquo we have more projects, and now we are focused on working in version 2.0.

**Comment by xoan** [comment]
Closed? Why? Because the bug is fixed, or because the bug won't be fixed? Or because the issue seems to be a support forum and you don't support any request?

This is very bad, IMHO.

**Comment by soyjavi** [comment]
Correct sintaxis:

LUNGO.Router.article("#copyright","#test");

# >> ID Selector

In LungoJS2 ((tapquo right now is working on it) There is a new pattern optimized for routing. patience :)
