### ISSUE TITLE
2 rooting same error

### ISSUE THREAD

**Issue by jhg** [tapquo/Lungo.js#86]
With Lungo 1.2 if in the app rooting 2 time to same secction the screen is black.

**Comment by soyjavi** [comment]
It is incongruous ... if you were in a section you have to use lng.router.back to return ... is basic in mobile UX / navigation.

**Comment by jhg** [comment]
No, I don't speak about back, I write program that use Barcoder Scanner of Phonegap and, if result is one or other routing to one section or other section, if two time to same section the screem is black and not work more.
