### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by Jumiluz** [tapquo/Lungo.js#9]
I'm pulling my hairs trying to use some checkboxes on a list but it's not working.
Do you guys have any ideas or is it just a bug?

Thanks in advance!

**Comment by soyjavi** [comment]
We'll introduce a new type of checkboxes (as iphone style)... Wait to v1.0.1

**Comment by soyjavi** [comment]
New type of checboxes & radio with this commit https://github.com/TapQuo/Lungo.js/commit/4eea386746098b5a191bc8cae0e0fe6036c58811
