### ISSUE TITLE
lng.Data.Storage.session('key', '') doesn't store the value

### ISSUE THREAD

**Issue by FdezRomero** [tapquo/Lungo.js#95]
The current implementation of `lng.Data.Storage.session` doesn't allow to empty a key by using `lng.Data.Storage.session('key', '');` as it checks for the value in order to know which action to perform. It should therefore distinguish between `(value === undefined)` for retrieving the value, and everything else for storing:

``` javascript
    var _handler = function(storage, key, value) {
        var storage = window[storage];

        if (value) { // My suggestion: if (value === undefined)
            _saveKey(storage, key, value);
        } else {
            return _getKey(storage, key, value);
        }
    };
```

**Comment by soyjavi** [comment]
FIxed in 2.0 version :)
