### ISSUE TITLE
Update LungoJS Online Demo code

### ISSUE THREAD

**Issue by ngduc** [tapquo/Lungo.js#97]
Hi,
LungoJS framework's demo has been listed on http://frameworkdemos.com
It's a free service to list all popular frameworks' demos so that users can try them on their mobile devices without looking for links around the internet.

Could you verify it and if possible, update LungoJS's demo source code at:
https://github.com/ngduc/framework-demos

Please let me know if there is any problem with my setup. Thanks.
Regards,
Duc

**Comment by soyjavi** [comment]
Please update your info with Lungo2 http://lungo.tapquo.com
