### ISSUE TITLE
lng.View.Template.List.create inside div tag 

### ISSUE THREAD

**Issue by clementprem** [tapquo/Lungo.js#98]
By using
lng.View.Template.List.create 
, how can I populate a list within a <div> tag.. (the div tag is inside an article).

**Comment by phil-hudson** [comment]
This is how I do it:

 var courses = {
        el: '#searchContent div#courseResults', //<------- look here
        template: 'coursesEmpty',
        data: {error: 'No courses'}
    }; 
    lng.View.Template.List.create(courses);

**Comment by soyjavi** [comment]
Lungo.View.Template is discontinued... welcome to our project Monocle http://monocle.tapquo.com
